# Group Настройки компании
На данный момент можно только получить информацию о текущих настройках компании. Создавать новые настройки или изменять существующие пока невозможно.
## Настройки компании [/entity/companysettings]
### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) о Настройках компании
+ **currency** - Ссылка на стандартную валюту в формате [Метаданных](#header-метаданные)
+ **discountStrategy** - Cовместное применение скидок. Может принимать значения `[bySum, byPriority]` означающие "Сумма скидок" и "Приоритетная" соответственно. `Необходимое`
  - *"Сумма скидок"* `[bySum]` означает, что должна действовать сумма скидок
  - *"Приоритетная"* `[byPriority]` должна действовать одна, наиболее выгодная для покупателя скидка

### Метаданные настроек
В метаданных Настроек компании, в поле **customEntities** показан список пользовательских справочников.
Каждый пользовательский справочник содержит поля:
+ **meta** - Ссылка на представление пользовательского справочника
+ **entityMeta** - Ссылка на список сущностей данного пользовательского справочника
+ **name** - Наименование справочника

### Получить Настройки компании [GET]
Запрос на получение Настроек компании.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Настроек компании.
  + Body
        <!-- include(body/companysettings/get.json) -->

## Метаданные настроек компании [/entity/companysettings/metadata]
### Получить метаданные настроек компании [GET]
Запрос на получение метаданных Настроек компании.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление метаданных настроек компании.
  + Body
        <!-- include(body/companysettings/metadata.json) -->
