# Group Контрагент
## Контрагенты [/entity/counterparty]
Средствами JSON API можно создавать и обновлять сведения о Контрагентах, запрашивать списки Контрагентов и сведения по отдельным Контрагентам. Счетами Контрагента и его контактными лицами можно управлять как в составе отдельного Контрагента, так и отдельно - с помощью специальных ресурсов для управления счетами и контактными лицами Контрагента. Кодом сущности для Контрагента в составе JSON API является ключевое слово **counterparty**. Больше о Контрагентах и работе с ними в основном интерфейсе вы можете прочитать в нашей службе поддержки по [этой ссылке](https://support.moysklad.ru/hc/ru/articles/203053486-%D0%A1%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D1%87%D0%BD%D0%B8%D0%BA-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%B3%D0%B5%D0%BD%D1%82%D0%BE%D0%B2).
По данной сущности можно осуществлять контекстный поиск с помощью специального параметра `search`. Подробнее можно узнать по [ссылке](#header-контекстный-поиск).

Поиск среди объектов Контрагента осуществляется по нескольким условиям. Если значения полей контрагента удовлетворяют хотя бы одному из условий, то контрагент будет найден.

Первое условие поиска:
+ По наименованию Контрагента **name**
+ По коду Контрагента **code**
+ По полному наименованию Контрагента **legalTitle**
+ По номеру дисконтной карты Контрагента **discountCardNumber**
+ По адресу электронной почты **email**
+ По комментарию **description**
+ По номеру городского телефона **phone**

Второе условие поиска по всем событиям контрагента:
+ По тексту событий контрагента **description**

Третье условие поиска по полям из всех контактных лиц фирмы контрагента (contactpersons):
+ По имени контактного лица **name**
+ По почте контактного лица **email**
+ По номеру телефона контактного лица **phone**


### Атрибуты сущности

+ **meta** - [Метаданные](#header-метаданные) объекта
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **owner** - Ссылка на Владельца (Сотрудника) в формате [Метаданных](#header-метаданные)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника в формате [Метаданных](#header-метаданные)
+ **syncId** - ID синхронизации. После заполнения недоступен для изменения.
+ **version** - Версия сущности. Изменяется при обновлении Контрагента `Только для чтения`
+ **updated** - Момент последнего обновления Контрагента `Только для чтения`
+ **name** - Наименование Контрагента `Необходимое`
+ **description** - Комментарий к Контрагенту
+ **code** - Код Контрагента
+ **externalCode** - Внешний код Контрагента `Только для чтения`
+ **archived** - Добавлен ли Контрагент в архив
+ **created** - Дата создания
+ **email** - Адрес электронной почты
+ **phone** - Номер городского телефона
+ **fax** - Номер факса
+ **actualAddress** - Фактический адрес Контрагента
+ **actualAddressFull** - Фактический адрес Контрагента с детализацией по отдельным полям.
+ **accounts** - Ссылка на счета Контрагента (массив)
+ **companyType** - Тип Контрагента. `[Юридическое лицо, Индивидуальный предприниматель, Физическое лицо]`.
В зависимости от значения данного поля набор выводимых реквизитов контрагента может меняться. Подробнее [тут](#header-тип-контрагента)
+ **discountCardNumber** - номер дисконтной карты Контрагента
+ **state** - Статус Контрагента в формате [Метаданных](#header-метаданные)
+ **salesAmount** - Сумма продаж `Только для чтения`
<h3>Поля реквизитов</h3>
___
+ **legalTitle** - Полное наименование для Контрагента типа `[Юридическое лицо]`. Игнорируется для Контрагентов типа `[Индивидуальный предприниматель, Физическое лицо]`, если передано одно из значений для ФИО и формируется автоматически на основе получаемых ФИО Контрагента.
+ **legalLastName** - Фамилия для Контрагента типа `[Индивидуальный предприниматель, Физическое лицо]`. Игнорируется для Контрагентов типа `[Юридическое лицо]`.
+ **legalFirstName** - Имя для Контрагента типа `[Индивидуальный предприниматель, Физическое лицо]`. Игнорируется для Контрагентов типа `[Юридическое лицо]`.
+ **legalMiddleName** - Отчество для Контрагента типа `[Индивидуальный предприниматель, Физическое лицо]`. Игнорируется для Контрагентов типа `[Юридическое лицо]`.
+ **legalAddress** - Юридический адрес Контрагента
+ **legalAddressFull** -  Юридический адрес Контрагента с детализацией по отдельным полям.
+ **inn** - ИНН
+ **kpp** - КПП
+ **ogrn** - ОГРН
+ **ogrnip** - ОГРНИП
+ **okpo** - ОКПО
+ **certificateNumber** - Номер свидетельства
+ **certificateDate** - Дата свидетельства
___
+ **tags** - Группы (массив)
+ **contactpersons** - Ссылка на контактные лица фирмы Контрагента (массив)
+ **attributes** - Коллекция доп. полей в формате [Метаданных](#header-метаданные)
+ **discounts** - Массив ссылок на скидки в формате [Метаданных](#header-метаданные) `Только для чтения`

Массив может содержать персональные и накопительные скидки. Персональная скидка выводится, если хотя бы раз изменялся **процент скидки** для контрагента, значение будет указано в поле **personalDiscount**.
Накопительная скидка выводится, если для контрагента хотя бы раз устанавливалась **коррекция суммы накоплений по скидке**, значение будет указано в поле **demandSumCorrection**. Формат вывода скидок можно посмотреть в разделе [Скидки](#скидки).
+ **notes** - Массив ссылок на события Контрагента в формате [Метаданных](#header-метаданные)
+ **priceType** - Тип цены Контрагента (строка или null)

### Атрибуты вложенных сущностей
#### Аттрибуты сущности Адрес
+ **postalCode** - Почтовый индекс
+ **country** - Ссылка на страну в формате [Метаданных](#header-метаданные)
+ **region** - Ссылка на регион в формате [Метаданных](#header-метаданные)
+ **city** - Город
+ **street** - Улица
+ **house** - Дом (Максимальная длина - 30 символов)
+ **apartment** - Квартира (Максимальная длина - 30 символов)
+ **addInfo** - Другое
+ **comment** - Комментарий

Строка адреса является конкатенацией полей структурированного адреса в следующем порядке: postalCode -> country -> region -> city -> street -> house -> apartment -> addInfo, используя запятую в качестве разделителя.
При передаче в МойСклад сущностей с адресом используйте либо строковый адрес, либо структурированнй.
При передаче обоих адресов строковый будет игнорирован.
При передаче только строкового он будет отражаться как в строковом поле, так и в addInfo структурированного адреса.

#### Счета Контрагентов
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **version** - Версия сущности. Изменяется при обновлении Контрагента `Только для чтения`
+ **updated** - Момент последнего обновления Контрагента `Только для чтения`
+ **isDefault** - Является ли счёт основным счётом Контрагента
+ **accountNumber** - Номер счёта `Необходимо`
+ **bankName** - Наименование банка
+ **bankLocation** - Адрес банка
+ **correspondentAccount** - Корр счет
+ **bic** - БИК

#### Контактные лица Контрагентов
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **version** - Версия сущности. Изменяется при обновлении Контрагента `Только для чтения`
+ **updated** - Момент последнего обновления Контрагента `Только для чтения`
+ **name** - ФИО контактного лица `Необходимое`
+ **description** - Описание контактного лица
+ **externalCode** - Внешний код контактного лица
+ **email** - Адрес электронной почты контактного лица
+ **phone** - Номер телефона контактного лица
+ **position** - Должность контактного лица
+ **agent** - Ссылка на Контрагента (тип [Мета](#header-метаданные))

#### События Контрагента
+ **meta** - [Метаданные](#header-метаданные) объекта
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **version** - Версия сущности. Изменяется при обновлении/удалении события Контрагента `Только для чтения`
+ **created** - Момент создания события Контрагента `Только для чтения`
+ **description** - Текст события Контрагента `Необходимое`
+ **agent** - Ссылка на Контрагента (тип [Мета](#header-метаданные)) `Только для чтения`
+ **author** - Создатель события, ссылка на сотрудника (тип [Мета](#header-метаданные)) `Только для чтения`

### Тип Контрагента
В зависимости от типа контрагента **companyType** в составе его объекта будут выводиться разные наборы реквизитов.
Типы контрагента и соответствующие значения, которые могут быть переданы в данном поле:
| Тип контрагента                | Значение поля companyType  |
| ------------------------------ |:---------------------------|
| Юридическое лицо               | legal                      |
| Индивидуальный предприниматель | entrepreneur               |
| Физическое лицо                | individual                 |

Если тип контрагента `Юридическое лицо`, будут выведены следующие поля реквизитов:
+ **legalTitle** - Полное наименование Контрагента
+ **legalAddress** - Юридический адрес Контрагента
+ **inn** - ИНН
+ **kpp** - КПП
+ **ogrn** - ОГРН
+ **okpo** - ОКПО

Если тип контрагента `Индивидуальный предприниматель`, будут выведены следующие поля реквизитов:
+ **legalTitle** - Полное наименование. Игнорируется, если передано одно из значений для ФИО. Формируется автоматически на основе получаемых ФИО Контрагента
+ **legalLastName** - Фамилия Контрагента
+ **legalFirstName** - Имя Контрагента
+ **legalMiddleName** - Отчество Контрагента
+ **legalAddress** - Юридический адрес Контрагента
+ **inn** - ИНН
+ **okpo** - ОКПО
+ **ogrnip** - ОГРНИП
+ **certificateNumber** - Номер свидетельства
+ **certificateDate** - Дата свидетельства

Если тип контрагента `Физическое лицо`, будут выведены следующие поля реквизитов:
+ **legalTitle** - Полное наименование. Игнорируется, если передано одно из значений для ФИО. Формируется автоматически на основе получаемых ФИО Контрагента
+ **legalLastName** - Фамилия Контрагента
+ **legalFirstName** - Имя Контрагента
+ **legalMiddleName** - Отчество Контрагента
+ **legalAddress** - Юридический адрес Контрагента
+ **inn** - ИНН

О работе с доп. полями Контрагентов можно прочитать [здесь](#header-работа-с-дополнительными-полями)

### Атрибуты доступные для фильтрации
+ **id** - ID в формате UUID
+ **owner** - Ссылка на Владельца (Сотрудника)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника
+ **syncId** - ID синхронизации
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления Контрагента
+ **updatedBy** - Автор последнего обновления сущности в формате `uid` (`admin@admin`)
+ **name** - Наименование Контрагента
+ **description** - Комментарий к Контрагенту
+ **code** - Код Контрагента
+ **externalCode** - Внешний код Контрагента
+ **archived** - Добавлен ли Контрагент в архив
+ **created** - Дата создания
+ **email** - Адрес электронной почты
+ **phone** - Номер городского телефона
+ **fax** - Номер факса
+ **actualAddress** - Фактический адрес Контрагента
+ **companyType** - Тип Контрагента
+ **discountCardNumber** - номер дисконтной карты Контрагента
+ **state** - Статус Контрагента
+ **legalTitle** - Полное наименование Контрагента
+ **legalAddress** - Юридический адрес Контрагента
+ **inn** - ИНН
+ **kpp** - КПП
+ **priceType** - Тип цены Контрагента (строка или null)

### Атрибуты доступные для сортировки
+ **id** - ID в формате UUID
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления Контрагента
+ **updatedBy** - Автор последнего обновления сущности в формате `uid` (`admin@admin`)
+ **name** - Наименование Контрагента
+ **description** - Комментарий к Контрагенту
+ **externalCode** - Внешний код Контрагента
+ **archived** - Добавлен ли Контрагент в архив
+ **created** - Дата создания
+ **email** - Адрес электронной почты
+ **phone** - Номер городского телефона
+ **fax** - Номер факса

### Получить список Контрагентов [GET]
Получить список всех Контрагентов.
Результат: Объект JSON, включающий в себя поля:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой Контрагентов.

+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Контрагентов.
  + Body
        <!-- include(body/counterparty/get_list.json) -->

### Создать Контрагента [POST]
Создать нового Контрагента
### Описание
Контрагент создаётся на основе переданного объекта JSON,
который содержит представление нового Контрагента.
+ Request Пример 1 (application/json)
Пример типичного запроса для создания Контрагента.
  + Body
        <!-- include(body/counterparty/post_request1.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Контрагента.
    + Body
          <!-- include(body/counterparty/post_request2.json) -->


+ Request Пример 2 (application/json)
Пример запроса на создание Контрагента с указанием только лишь его имени
  + Body
        <!-- include(body/counterparty/post_short.json) -->


+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Контрагента.
  + Body
        <!-- include(body/counterparty/post_short_response.json) -->

+ Request Пример 3 (application/json)
Пример запроса на создание Контрагента с указанием юридических реквизитов для типа Индивидуальный Предприниматель.
  + Body
        <!-- include(body/counterparty/post_entrepreneur_names_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Контрагента.
  + Body
        <!-- include(body/counterparty/post_entrepreneur_names_response.json) -->

+ Request Пример с доп полями (application/json)
Пример запроса для создания Контрагента с доп полями в теле запроса.
    + Body
          <!-- include(body/counterparty/post_with_attributes_request.json) -->


+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Контрагента.
    + Body
          <!-- include(body/counterparty/post_with_attributes_response.json) -->

### Удалить Контрагента [DELETE /entity/counterparty/{id}]
Запрос на удаление Контрагента с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Контрагента

+ Response 200 (application/json)
Успешное удаление Контрагента.
  + Body

## Метаданные Контрагентов [/entity/counterparty/metadata]
### Метаданные Контрагентов [GET]
Запрос на получение метаданных Контрагентов. Результат - объект JSON, включающий в себя:
+ **meta** - Ссылка на метаданные Контрагентов
+ **attributes** - Массив объектов доп. полей Контрагентов в формате [Метаданных](#header-метаданные)
+ **states** - Массив статусов Контрагентов
+ **createShared** - создавать новых Контрагентов с меткой "Общий"

Структура отдельного объекта, представляющего доп. поле подробно описана в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями).

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление доп. полей Контрагентов.
  + Body
        <!-- include(body/counterparty/get_metadata.json) -->

## Отдельное доп. поле [/entity/counterparty/metadata/attributes/{id}]
+ Parameters
  + id: `5290a290-0313-11e6-9464-e4de00000020` (required, string) - id Доп. поля
### Отдельное доп. поле [GET]
Запрос на получение информации по отдельному дополнительному полю.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельного доп. поля.
  + Body
        <!-- include(body/counterparty/metadata_by_id.json) -->

## Контрагент [/entity/counterparty/{id}]
Контрагент, обращение к которому происходит по значению его id.

+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Контрагента.

### Получить Контрагента [GET]
Возвращает JSON представление Контрагента с указанным id.

+ Request Пример 1
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Контрагента с указанным id.
  + Body
        <!-- include(body/counterparty/get_by_id.json) -->

+ Request Пример 2
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Контрагента типа Индивидуальный Предприниматель с указанным id.
  + Body
        <!-- include(body/counterparty/get_entrepreneur_by_id.json) -->

### Изменить Контрагента [PUT]
### Описание
Обновляется представление Контрагента с указанным id.
В теле запроса можно указать только те поля, которые необходимо изменить у Контрагента, кроме тех, что
помечены `Только для чтения` в описании [атрибутов Контрагента](#контрагент-контрагенты).
Поля, которые не были указаны в JSON запроса, не изменяются.
Поля **account** и **contactpersons** обновляются как элементы вложенных коллекций. При обновлении,
переданные элементы данных коллекций обрабатываются как "Все элементы данной коллекции" и полностью заменяют
элементы, ранее присутствовавшие в ней.

+ Request Пример (application/json)
В теле запроса можно указать только те поля, которые необходимо изменить у Контрагента
+ Body
    <!-- include(body/counterparty/put_request.json) -->

+ Response 200 (application/json)
Успешное обновление. Результат - JSON представление обновлённого Контрагента.
  + Body
      <!-- include(body/counterparty/put_response.json) -->

+ Request Пример c доп полями(application/json)
Пример запроса для обновления Контрагента с доп полями в теле запроса.
    + Body
          <!-- include(body/counterparty/put_with_attributes_request.json) -->

+ Response 200 (application/json)
Успешное обновление. Результат - JSON представление обновлённого Контрагента.
  + Body
      <!-- include(body/counterparty/put_with_attributes_response.json) -->

## Счета Контрагента [/entity/counterparty/{id}/accounts]
Список счетов Контрагента с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Контрагента.

### Получить счета Контрагента [GET]
Возвращает массив JSON представлений счетов Контрагента.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`


+ Response 200 (application/json)
Успешный запрос.
  + Body
      <!-- include(body/counterparty/get_accounts.json) -->

## Счет Контрагента [/entity/counterparty/{id}/accounts/{accountId}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Контрагента.
  + accountId: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Счёта.

### Получить счет Контрагента [GET]
Возвращает JSON представление счета Контрагента.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`
+ Response 200 (application/json)
Успешный запрос.
  + Body
      <!-- include(body/counterparty/get_account.json) -->

## Контактные лица Контрагента [/entity/counterparty/{id}/contactpersons]
Получить список контактных лиц Контрагента с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Контрагента.

### Список контактных лиц [GET]
Возвращает массив JSON представлений контактных лиц Контрагента.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос.
  + Body
        <!-- include(body/counterparty/get_contactpersons.json) -->

### Создать контактное лицо[POST]
Создать контактное лицо Контрагента с указанным id.

+ Request Пример (application/json)
Пример запроса на создание контактного лица Контрагента.
  + Body
      <!-- include(body/counterparty/post_contactperson.json) -->

+ Response 200 (application/json)
Успешное создание.
  + Body
      <!-- include(body/counterparty/post_contactperson_response.json) -->

## Контактное лицо [/entity/counterparty/{id}/contactpersons/{contactpersonId}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Контрагента.
  + contactpersonId: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id контактного лица.

### Получить контактное лицо [GET]
Возвращает JSON представление отдельного контактного лица Контрагента.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос.
  + Body
      <!-- include(body/counterparty/get_contactperson.json) -->
### Изменить контактное лицо[PUT]
### Описание
Обновить контактное лицо Контрагента с указанным id.
Обновляются все поля, указанные в JSON объекте запроса, кроме
помеченных `Только для чтения` в описании [атрибутов контактных лиц Контрагента](#header-контактные-лица-контрагентов).
Поля, которые не были указаны в JSON запроса, не изменяются.
+ Parameters
  + contactpersonId: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id контактного лица.
+ Request Пример (application/json)
Пример запроса на обновление контактного лица Контрагента.
  + Body
      <!-- include(body/counterparty/put_contactperson.json) -->

+ Response 200 (application/json)
Успешное обновление.
  + Body
      <!-- include(body/counterparty/put_contactperson_response.json) -->

## События Контрагента [/entity/counterparty/{id}/notes]
Получить список событий Контрагента с указанным id.
+ Parameters
  + id: `67e5a691-3c9c-11e7-8af5-581e00000056` (required, string) - id Контрагента.

### Список событий [GET]
Возвращает массив JSON представлений событий Контрагента.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос.
  + Body
        <!-- include(body/counterparty/get_notes.json) -->

### Добавить событие [POST]
+ Request Пример (application/json)
Запрос на добавление нового события.
  + Body
        <!-- include(body/counterparty/post_note_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление добавленного события.
  + Body
        <!-- include(body/counterparty/post_note_response.json) -->

## Событие [/entity/counterparty/{id}/notes/{noteId}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Контрагента.
  + noteId: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id события.

### Получить событие [GET]
Возвращает JSON представление отдельного события Контрагента.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Контрагента.
  + noteId: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id события.

+ Response 200 (application/json)
Успешный запрос.
  + Body
      <!-- include(body/counterparty/get_note.json) -->
### Изменить событие [PUT]
### Описание
Обновить событие Контрагента с указанным id.
Обновляются все поля, указанные в JSON объекте запроса, кроме
помеченных `Только для чтения` в описании [атрибутов событий Контрагента](#header-события-контрагента).
Поля, которые не были указаны в JSON запроса, не изменяются.
+ Request Пример (application/json)
Пример запроса на обновление события Контрагента.
  + Body
      <!-- include(body/counterparty/put_note.json) -->

+ Response 200 (application/json)
Успешное обновление.
  + Body
      <!-- include(body/counterparty/put_note_response.json) -->

### Удалить событие [DELETE]
Запрос на удаление события с указанным id.
+ Parameters
  + id: `67e5a691-3c9c-11e7-8af5-581e00000056` (required, string) - id Контрагента.
  + noteId: `50b318cb-3cb0-11e7-8af5-581e00000007` (required, string) - id события

+ Response 200 (application/json)
Успешное удаление События.
  + Body

# Data Structures
## Counterparty Accounts request (object)
###Properties
+ id: `24124124-4124-4124124` (string, required) - ID в формате UUID
+ version: 1(string, optional) - Версия сущности
+ updated: `2016-04-04 12:20:10`(string, optional) - Момент последнего обновления сущности
+ isDefault: false (boolean, optional) - Является ли счет счетом по умолчанию
+ accountNumber: `1234567876543` (string, optional) - Номер счёта
+ bankname: "ОАО Сбербанк" (string, optional) - Наименование банка
+ bankLocation: `г Москва` (string, optional) - Адрес банка
+ correspondentAccount: `1231412412451` (string, optional) - Корр счет
+ bic: `214124` (string, optional) - БИК

## Counterparty_Entity (object)
###Properties
+ meta:(MetaRef) - Метаданные
+ id: `24124124-4124-4124124` (string) - ID в формате UUID
+ accountId: `121252-12412-4124141-24124`(string) - ID учетной записи
+ version: 1(string, optional) - Версия сущности
+ updated: `2016-04-04 12:20:10`(string, optional) - Момент последнего обновления сущности
+ deleted: `2016-04-04 12:20:10`(string, optional) - Момент последнего удаления сущности
+ name: Supplier(string) - Имя Контрагента
+ description: best CP ever(string) - Описание Контрагента
+ code: 124(string)
+ externalCode: 456(string, optional)
+ email: mail@mail.ru(string, optional) - Эл почта
+ phone: 12412512(string) - Номер телефома
+ fax: oloo(string, optional) - Факс
+ actualAddress: lol (string, optional) - Адрес
+ accounts:(Meta, fixed, optional) - Счета Контрагента
+ legalTitle: `ООО "Покупатель"` (string, optional)- Полное наименование
+ legalAddress: `г Москва ул Вавилова д 19 к 101` (string, optional) - Юридический адрес
+ inn: `8435678011` (string, optional) - ИНН
+ kpp: `153215325` (string, optional) - КПП
+ ogrn: `13251325132` (string, optional) - ОГРН
+ okpo: `123512351325` (string, optional) - ОКПО
+ tags: (array[string], optional, fixed) - Группы контрагента
+ contactpersons: (Meta, fixed, optional) - Контактные лица

## Counterparty list (object)
###Properties
+ context: (Context, required)
+ meta: (Meta, required)
+ rows: (array[Counterparty_Entity], required, fixed) - Массив Контрагентов

## Counterparty response2 (Counterparty_Entity)
+ meta: (MetaRef) - MetaData
+ id: `47124-412412-4124-42141-421`(string) - ID в формате UUID
+ version: 1(string) - Версия сущности
+ updated: `2016-04-04 12:20:10`(string) - Момент последнего обновления сущности
+ accountId: `121252-12412-4124141-24124`(string) - ID учетной записи
+ name: myName(string) - Имя Контрагента
+ externalCode: exK8Z7EIhhDpX0VPeVXTb0(string) - Внешний коды
+ accounts:(array[AgentAccount], fixed) - Счета Контрагента

## Accounts List (object)
###Properties
+ context: (Context, required)
+ meta: (Meta, required)
+ rows: (array[AgentAccount], required, fixed) - Массив Счетов

## Contacpersons List (object)
###Properties
+ context: (Context, required)
+ meta: (Meta, required)
+ rows: (array[ContactPerson], required, fixed) - Массив Контактных лиц

## Counterparty request (object)
+ name: myName (string, required) - Имя агента
+ code: one1 (string, optional) - Кодовый идентификатор
+ email: sayhello@mail.com (string, optional) - E-mail
+ phone: 87262761824 (string, optional) - Телефон
+ fax: 124124 (string, optional) - Факс
+ actualAddress: г Москва ул. Вавилова д 19 (string, optional) - Адрес

## Counterparty request short (object)
+ name:   myName (string, required) - Имя контрагента

## Legendable Entity (object)
###Properties
+ meta:(MetaRefWithMetaData, optional) - Метаданные
+ id: `24124124-4124-4124124` (string, optional) - ID в формате UUID
+ accountId: `121252-12412-4124141-24124`(string, optional) - ID учетной записи
+ version: 1(string, optional) - Версия сущности
+ updated: `2016-04-04 12:20:10`(string, optional) - Момент последнего обновления сущности
+ deleted: `2016-04-04 12:20:10`(string, optional) - Момент последнего удаления сущности
+ name: Товар1 (string, optional) - Наименование Заказа Покупателя
+ description: Это товар 1(string, optional) - Описание
+ code: 124(string, optional) - Код
+ externalCode: 456(string, optional) - Внешний код
+ archived: true (boolean, optional) - Добавлена операция в архив
