

<h3><a name="обработка-ошибок-1000"></a>1000</h3>
+ **Сообщение**: *Элемент URI не является идентификатором*
+ **Описание**: Вероятнее всего вы пытаетесь обратиться к несуществующему ресурсу. Проверьте
  указанный вами URI, проверьте правильно ли вы указали ключевое слово сущности и полностью ли вы скопировали ID.

<h3><a name="обработка-ошибок-1001"></a>1001</h3>
+ **Сообщение**: *Не указан идентификатор метаданных*
+ **Описание**: При обращении к пользовательскому справочнику в URI должен быть указан корректный {id} метаданных данного справочника.
Его можно уточнить, сделав запрос к метаданным настроек компании `companysettings/metadata` в массиве **customEntities**.

<h3><a name="обработка-ошибок-1002"></a>1002</h3>
+ **Сообщение**: *Неопознанный путь: {путь}*
+ **Описание**: Не удалось определить ресурс, по которому был сделан запрос. Проверьте URI по которому совершается запрос.

<h3><a name="обработка-ошибок-1003"></a>1003</h3>
+ **Сообщение**: *Отсутствуют метаданные для типа {тип}*
+ **Описание**: Для данного ресурса нельзя получить метаданные. Ещё раз проверьте документацию по сущности данного типа и убедитесь в наличии ресурса "Метаданные <наименование_сущности>"

<h3><a name="обработка-ошибок-1004"></a>1004</h3>
+ **Сообщение**: *Ошибка при формировании результата: {текст ошибки}*
+ **Описание**: При разборе переданного объекта произошла ошибка. Проверьте корректность переданных данных.

<h3><a name="обработка-ошибок-1005"></a>1005</h3>
+ **Сообщение**: *Неизвестный тип: {тип}*
+ **Описание**: Тип сущности, указанный в URI, не может быть найден. Проверьте корректность ключевого слова.

<h3><a name="обработка-ошибок-1006"></a>1006</h3>
+ **Сообщение**: *Создание объектов с указанным идентификатором запрещено*
+ **Описание**: При создании сущности не нужно указывать в URI запроса id сущности. Запрос на создание должен происходить по тому же URI, по которому происходит запрос на получение списка сущностей данного типа.

<h3><a name="обработка-ошибок-1007"></a>1007</h3>
+ **Сообщение**: *Неизвестное поле: {имя поля}*
+ **Описание**: При обновлении сущности указанное поле не было найдено. Проверьте правильность написания имени поля, а также убедитесь что данное поле присутствует среди атрибутов сущностей этого типа.

<h3><a name="обработка-ошибок-1008"></a>1008</h3>
+ **Сообщение**: *Ошибка при загрузке объекта с типом '{тип}' и идентификатором '{id}'*
+ **Описание**:  Не удалось загрузить сущность с данным id. Проверьте корректность id. Убедитесь что сущность с данным id присутствует среди списка сущностей данного типа (возможно сущность с данным id была удалена).

<h3><a name="обработка-ошибок-1009"></a>1009</h3>
+ **Сообщение**: *Редактирование объектов типа '{тип}' не поддерживается*
+ **Описание**: Сущность которую вы пытаетесь обновить - только для чтения. Изменение её атрибутов не предусмотрено.

<h3><a name="обработка-ошибок-1010"></a>1010</h3>
+ **Сообщение**: *Удаление объектов типа '{тип}' не поддерживается*
+ **Описание**: Нельзя удалить сущность данного типа. Проверьте, есть ли среди операций данного типа сущностей операция удаления.

<h3><a name="обработка-ошибок-1011"></a>1011</h3>
+ **Сообщение**: *Создание объектов типа '{тип}' не поддерживается*
+ **Описание**: Нельзя создать сущность данного типа. Проверьте, есть ли среди операций данного типа сущностей операция создания.

<h3><a name="обработка-ошибок-1012"></a>1012</h3>
+ **Сообщение**: *Не указан идентификатор объекта*
+ **Описание**: Для операций обновления и удаления необходимо указывать id сущности, над которой производится операция.

<h3><a name="обработка-ошибок-1013"></a>1013</h3>
+ **Сообщение**: *Удаление вложенных объектов не поддерживается*
+ **Описание**: Невозможно удалить вложенные сущности, такие как счета контрагентов. Если вы хотите обнулить значение поля: попробуйте передать null в качестве значения данного поля в запроса не обновление. В случае с позициями документов - вы можете передать пустой массив. Это будет эквивалентно удалению сразу всех позиций из документа.

<h3><a name="обработка-ошибок-1014"></a>1014</h3>
+ **Сообщение**: *Неверное значение '{значение}' параметра фильтрации '{имя параметра}'*
+ **Описание**: Вы указали значение неподдерживаемого типа для данного параметра (например передали int вместо boolean). Возможно ошибка в неправильном формате даты и времени.

<h3><a name="обработка-ошибок-1015"></a>1015</h3>
+ **Сообщение**: *Указана неверная версия в url: {url}*
+ **Описание**: Проверьте необходимую версию API в url по которому вы делаете запрос. `online.moysklad.ru/api/1.x/...` Версии API различаются между собой по количеству
доступных ресурсов, а также по способу обработки данных и именно поэтому являются важным элементом идентификации того или иного ресурса.

<h3><a name="обработка-ошибок-1016"></a>1016</h3>
+ **Сообщение**: *Доступ запрещен: у вас нет прав на просмотр данного объекта*
+ **Описание**: Администратор учётной записи ограничил ваши права на просмотр сущностей данного типа. Свяжитесь с ним для выяснения подробностей.

<h3><a name="обработка-ошибок-1017"></a>1017</h3>
+ **Сообщение**: *Доступ запрещен: у вас нет прав на редактирование данного объекта*
+ **Описание**: Администратор учётной записи ограничил ваши права на редактирование сущностей данного типа. Свяжитесь с ним для выяснения подробностей.

<h3><a name="обработка-ошибок-1018"></a>1018</h3>
+ **Сообщение**: *Доступ запрещен: у вас нет прав на удаление данного объекта*
+ **Описание**: Администратор учётной записи ограничил ваши права на удаление сущностей данного типа. Свяжитесь с ним для выяснения подробностей.

<h3><a name="обработка-ошибок-1019"></a>1019</h3>
+ **Сообщение**: *Чтение поля '{имя поля}' не поддерживается*
+ **Описание**: Невозможно чтение поля данного типа.

<h3><a name="обработка-ошибок-1020"></a>1020</h3>
+ **Сообщение**: *Родительский объект с типом '{тип}' и идентификатором '{id}' не существует*
+ **Описание**: Неверный id родительской сущности.

<h3><a name="обработка-ошибок-1021"></a>1021</h3>
+ **Сообщение**: *Объект с типом '{тип}' и идентификатором '{id}' не найден*
+ **Описание**: Не удалось загрузить сущность данного типа с данным id. Проверьте корректность id. Убедитесь что сущность с данным id присутствует среди списка сущностей данного типа (возможно сущность с данным id была удалена)

<h3><a name="обработка-ошибок-1022"></a>1022</h3>
+ **Сообщение**: *Ошибка при создании объекта*
+ **Описание**: Ошибка в процессе создания сущности данного типа.

<h3><a name="обработка-ошибок-1023"></a>1023</h3>
+ **Сообщение**: *Ошибка сохранения объекта: дочерний объект с типом '{тип}' и идентификатором '{id}' уже используется и не может быть удален*
+ **Описание**: Невозможно удалить объект во вложенной коллекции т.к. он уже где-то используется. Например, может возникнуть при удалении позиции из документа, по которому есть возврат,
в котором присутствует данная позиция.

<h3><a name="обработка-ошибок-1024"></a>1024</h3>
+ **Сообщение**: *Ошибка сохранения объекта: изменять стандартные объекты запрещено*
+ **Описание**: Вы пытаетесь изменить сущность, которая создаётся по умолчанию в сервисе МойСклад сразу после регистрации учётной записи. Это делать запрещено. (Например изменение стандартных стран и единиц измерения)

<h3><a name="обработка-ошибок-1025"></a>1025</h3>
+ **Сообщение**: *Ошибка удаления объекта: удалять стандартные объекты запрещено*
+ **Описание**: Удаление стандартных объектов, таких как стандартные единицы измерения, валюты, страны и т.п. не поддерживается.

<h3><a name="обработка-ошибок-1026"></a>1026</h3>
+ **Сообщение**: *Обновление объектов типа '{тип}' не поддерживается*
+ **Описание**: Обновление объектов указанного типа не поддерживается в JSON API.

<h3><a name="обработка-ошибок-1027"></a>1027</h3>
+ **Сообщение**: *Запрос не содержит объектов*
+ **Описание**: Тело запросов на создание/обновление должно представляться в виде объекта либо массива JSON.

<h3><a name="обработка-ошибок-1028"></a>1028</h3>
+ **Сообщение**: *Объект уже используется и не может быть удален*
+ **Описание**: Сущность используется в сущностях и документах, перечисленных в ошибке, поэтому её нельзя удалить. Например нельзя удалить товар, который используется в качестве позиции в каком-либо документе.

<h3><a name="обработка-ошибок-1029"></a>1029</h3>
+ **Сообщение**: *Шаблоны для типа '{тип}' не поддерживаются*
+ **Описание**: Невозможно создать предзаполненную сущность данного типа.

<h3><a name="обработка-ошибок-1030"></a>1030</h3>
+ **Сообщение**: *Поле для фильтрации '{имя поля}' может быть указано только один раз*
+ **Описание**: Убедитесь, что каждое поле используется в параметрах фильтрации лишь единожды.

<h3><a name="обработка-ошибок-1031"></a>1031</h3>
+ **Сообщение**: *Ошибка генерации шаблона: невозможно создать шаблон объекта на основе указанных полей*
+ **Описание**: Невозможно создать предзаполненную сущность данного типа на основе другой.

<h3><a name="обработка-ошибок-1032"></a>1032</h3>
+ **Сообщение**: *Ошибка фильтрации: характеристика '{имя/id характеристики}' не существует*
+ **Описание**: У данной модификации нет характеристики с указанным id. Проверьте правильность введённого id и список характеристик для данной модификации.

<h3><a name="обработка-ошибок-1033"></a>1033</h3>
+ **Сообщение**: *Ошибка фильтрации: фильтрация по характеристикам модификаций совместима только с группировкой по модификациями*
+ **Описание**: В отчётах при передаче значения параметра **groupBy** отличного от `variant` невозможна фильтрация по характеристикам модификаций.

<h3><a name="обработка-ошибок-1034"></a>1034</h3>
+ **Сообщение**: *Ошибка фильтрации: {текст ошибки}*
+ **Описание**: Ошибка в процессе обработки фильтров. Проверьте переданные фильтры на валидность. Подробнее о параметрах фильтрации вы можете прочесть в соответствующем разделе документации или в документации по сущности, к которой вы пытаетесь применять фильтры.

<h3><a name="обработка-ошибок-1035"></a>1035</h3>
+ **Сообщение**: *Ошибка фильтрации: неверный формат даты параметра фильтрации*
+ **Описание**: Проверьте значение даты и времени. Оно должно соответствовать формату `yyyy-MM-dd HH:mm:ss`

<h3><a name="обработка-ошибок-1036"></a>1036</h3>
+ **Сообщение**: *Ошибка при формировании метаданных*
+ **Описание** Внутренняя ошибка сервиса. Попробуйте повторить запрос.

<h3><a name="обработка-ошибок-1037"></a>1037</h3>
+ **Сообщение**: *Неверно указан Content-Type запроса*
+ **Описание** Возможно ресурс, к которому вы обращаетесь, требует form-data вместо JSON (или наоборот).

<h3><a name="обработка-ошибок-1038"></a>1038</h3>
+ **Сообщение**: *Ошибка в адресе запроса*
+ **Описание** Проверьте, указываете ли вы валидный адрес запроса.

<h3><a name="обработка-ошибок-1039"></a>1039</h3>
+ **Сообщение**: *Операция {HTTP метод} не поддерживается для данного ресурса*
+ **Описание** Проверьте метод, с которым вы обращаетесь к ресурсу. Убедитесь, что в документации ресурса этот метод описан и его можно применить.

<h3><a name="обработка-ошибок-1040"></a>1040</h3>
+ **Сообщение**: *Неверно заданы параметры запроса*
+ **Описание** Один или несколько параметров запроса заданы некорректно. Проверьте формат параметров согласно документации.

<h3><a name="обработка-ошибок-1041"></a>1041</h3>
+ **Сообщение**: *Неверное значение '{значение}' параметра фильтрации '{имя параметра}', допустимые значения: '{список допустимых значений}'*
+ **Описание**: Значение параметра должно входить в список допустимых значений.

<h3><a name="обработка-ошибок-1042"></a>1042</h3>
+ **Сообщение**: *Неверное значение '{значение}' параметра сортировки '{имя параметра}', допустимые значения: '{список допустимых значений}'*
+ **Описание**: Значение параметра должно входить в список допустимых значений.

<h3><a name="обработка-ошибок-1043"></a>1043</h3>
+ **Сообщение**: *Ваш тарифный план не позволяет работать с CRM*
+ **Описание**: Ваш тариф не подходит для работы с CRM.

<h3><a name="обработка-ошибок-1044"></a>1044</h3>
+ **Сообщение**: *Превышен максимальный размер запроса*
+ **Описание**: Максимальный размер запроса 10 МБ.

<h3><a name="обработка-ошибок-1045"></a>1045</h3>
+ **Сообщение**: *Доступ запрещен: у вас нет прав на создание данного объекта*
+ **Описание**:  Администратор учётной записи ограничил ваши права на создание сущностей данного типа. Свяжитесь с ним для выяснения подробностей.

<h3><a name="обработка-ошибок-1046"></a>1046</h3>
+ **Сообщение**: *Дочерняя сущность не может изменять свою родительскую сущность*
+ **Описание**: Возможно вы попробовали подставить позицию(и) из одного документа в другой (Попробуйте удалить **meta**, **id**, **accountId** из документа и позиции(й)).

<h3><a name="обработка-ошибок-1047"></a>1047</h3>
+ **Сообщение**: *Вы не можете обновить поле syncId в запросе на обновление сущности*
+ **Описание**: Поле **syncId** может быть указано только при создании сущности. Его нельзя изменить в запросе на обновление.

<h3><a name="обработка-ошибок-1052"></a>1052</h3>
+ **Сообщение**: *Неверный формат UUID*
+ **Описание**: Проверьте сгенерированные вами UUID на корректность.

<h3><a name="обработка-ошибок-1056"></a>1056</h3>
+ **Сообщение**: *Ошибка аутентификации: {текст ошибки аутентификации}*
+ **Описание** Проверьте указанные для аутентификации данные. Возможно для данного ресурса требуется другой вид аутентификации.

<h3><a name="обработка-ошибок-1058"></a>1058</h3>
+ **Сообщение**: *Не удалось декодировать параметры запроса из URL*
+ **Описание** Проверьте запрос. Вероятно, в строке присутствуют параметры, которые не были **urlencoded**.

<h3><a name="обработка-ошибок-1059"></a>1059</h3>
+ **Сообщение**: *Некорректный сервер в идентификаторе объекта: '{идентификатор}'*
+ **Описание** Идентификатор объекта содержит сервер, отличный от online.moysklad.ru.

<h3><a name="обработка-ошибок-1060"></a>1060</h3>
+ **Сообщение**: *Некорректный тип данных в meta сущности, поле type*
+ **Описание** Тип данных указанный в поле type метаданных сущности не совпадает с ожидаемым типом.

<h3><a name="обработка-ошибок-1061"></a>1061</h3>
+ **Сообщение**: *Отсутствует доступ к API для данного пользователя*
+ **Описание** Отсутствует доступ к API для данного пользователя - обратитесь к администратору аккаунта.

<h3><a name="обработка-ошибок-1062"></a>1062</h3>
+ **Сообщение**: *Неверное значение заголовка 'Accept'. Поддерживается только значение 'application/json;charset=utf-8'*
+ **Описание** Значение заголовка 'Accept' может быть только application/json;charset=utf-8.

<h3><a name="обработка-ошибок-1063"></a>1063</h3>
+ **Сообщение**: *Ошибка сортировки: неизвестное поле '{название поля}' или сортировка для данного поля не поддерживается*
+ **Описание** Сортировка для данного поля не поддерживается. Возможно, поле не входит в список поддерживаемых полей.

<h3><a name="обработка-ошибок-1064"></a>1064</h3>
+ **Сообщение**: *Доступ запрещен: у вас нет прав на печать данных объектов*
+ **Описание** Администратор учётной записи ограничил ваши права на печать сущностей данного типа. Свяжитесь с ним для выяснения подробностей.

<h3><a name="обработка-ошибок-1065"></a>1065</h3>
+ **Сообщение**: *Ошибка сохранения объекта: объект уже изменен/удален в параллельном запросе*
+ **Описание** Ошибка возникает при попытке изменить объект из нескольких параллельных запросов к API.

<h3><a name="обработка-ошибок-1066"></a>1066</h3>
+ **Сообщение**: *Ошибка удаления объекта: объект нельзя переместить в корзину*
+ **Описание** Удаление в корзину возможно только для документов. Проверьте, является ли удаляемый объект документом.

<h3><a name="обработка-ошибок-1067"></a>1067</h3>
+ **Сообщение**: *Ошибка удаления объекта: использование корзины отключено*
+ **Описание** Отключена опция для удаления документов в корзину - обратитесь к администратору аккаунта.

<h3><a name="обработка-ошибок-1068"></a>1068</h3>
+ **Сообщение**: *Точка продаж отключена. Обратитесь к администратору аккаунта*
+ **Описание** Убедитесь, что Ваш тарифный план поддерживает работу с точками продаж.

<h3><a name="обработка-ошибок-1069"></a>1069</h3>
+ **Сообщение**: *Ошибка запроса: несовместимые параметры запроса: '{несовместимые параметры}'*
+ **Описание** Не все параметры запроса могут быть применены одновременно, они перечисленны в тексте ошибки: '{несовместимые параметры}'. Следует исключить параметры из запроса, учитывая совместимость.

<h3><a name="обработка-ошибок-1070"></a>1070</h3>
+ **Сообщение**: *Ошибка: ваш тарифный план не позволяет вам работать с данным ресурсом*
+ **Описание** На вашем тарифном плане работа с указанным ресурсом недоступна.

<h3><a name="обработка-ошибок-1071"></a>1071</h3>
+ **Сообщение**: *Превышено ограничение на количество попыток регистрации*
+ **Описание** Вы попытались зарегистрироваться слишком много раз

<h3><a name="обработка-ошибок-1072"></a>1072</h3>
+ **Сообщение**: *Превышено ограничение на количество регистраций с указанного адреса*
+ **Описание** Вы попытались зарегистрироваться слишком много раз

<h3><a name="обработка-ошибок-1073"></a>1073</h3>
+ **Сообщение**: *Превышено ограничение на одновременное количество запросов*
+ **Описание** От вас поступает слишком много параллельных запросов в единицу времени.

<h3><a name="обработка-ошибок-1074"></a>1074</h3>
+ **Сообщение**: *Сервис временно недоступен, ведутся технические работы*
+ **Описание** На сервере проводятся технические работы.

<h3><a name="обработка-ошибок-1083"></a>1083</h3>
+ **Сообщение**: *Ошибка при формировании результата: {текст ошибки}*
+ **Описание** При формировании ответа произошла ошибка на стороне сервера. Попробуйте повторить запрос заново.

<h3><a name="обработка-ошибок-1090"></a>1090</h3>
+ **Сообщение**: *Дополнительный справочник {название справочника} используется в: {названия документов} и не может быть удален*
+ **Описание** Дополнительный справочник используется как дополнительное поле в документах, перечисленных в ошибке.

<h3><a name="обработка-ошибок-1999"></a>1999</h3>
+ **Сообщение**: *Неизвестная ошибка*
+ **Описание** Произошла непредвиденная ошибка. Пожалуйста, обратитесь в поддержку сервиса МойСклад подробно изложив условия при которых эта ошибка произошла.

<h2>Ошибки формата</h2>
<h3><a name="обработка-ошибок-2000"></a>2000</h3>
+ **Сообщение**: *Ошибка формата: отсутствует начало объекта*
+ **Описание**: В данном месте ожидалось начало объекта. Проверьте тело запроса.

<h3><a name="обработка-ошибок-2001"></a>2001</h3>
+ **Сообщение**: *Ошибка формата: входящий запрос не соответствует формату JSON*
+ **Описание**: Данные должны быть отправлены в формате JSON. Если это так, а ошибка всё-таки возникает - попробуйте добавить Header `Content-Type` со значением `application/json`.

<h3><a name="обработка-ошибок-2002"></a>2002</h3>
+ **Сообщение**: *Ошибка формата: неименованное внутреннее поле типа массив*
+ **Описание**: Проверьте указали ли вы наименование поля типа массив. Возможно присутствуют лишние открывающиеся/закрывающиеся скобки в теле запроса.

<h3><a name="обработка-ошибок-2003"></a>2003</h3>
+ **Сообщение**: *Ошибка формата: неименованное внутреннее поле типа объект*
+ **Описание**: Проверьте указали ли вы наименование поля типа "объект". Возможно присутствуют лишние открывающиеся/закрывающиеся скобки в теле запроса.

<h3><a name="обработка-ошибок-2004"></a>2004</h3>
+ **Сообщение**: *Ошибка формата: вложенные массивы недопустимы*
+ **Описание**: В рамках JSON API не обрабатываются массивы массивов. Проверьте тело запроса на корректность.

<h3><a name="обработка-ошибок-2005"></a>2005</h3>
+ **Сообщение**: *Ошибка формата: входящий JSON должен начинаться либо с объекта, либо с массива*
+ **Описание**: Отсутствует открывающаяся фигурная/квадратная скобка в начале тела запроса.

<h3><a name="обработка-ошибок-2006"></a>2006</h3>
+ **Сообщение**: *Ошибка формата: слишком большая вложенность объектов*
+ **Описание**: Максимальная глубина вложенности в JSON API - 10. Скорректируйте тело запроса и убедитесь, что это ограничение не нарушается.

<h3><a name="обработка-ошибок-2007"></a>2007</h3>
+ **Сообщение**: *Ошибка формата: слишком большое число вложенных объектов*
+ **Описание**: В JSON API в массиве может содержаться не более 100 объектов.

<h3><a name="обработка-ошибок-2008"></a>2008</h3>
+ **Сообщение**: *Ошибка формата: запрос на шаблон не должен содержать массив*
+ **Описание**: С помощью запроса по ресурсу `{entity_name}/new` можно создать только 1 шаблон. Передача массива значений не поддерживается.

<h3><a name="обработка-ошибок-2009"></a>2009</h3>
+ **Сообщение**: *Ошибка формата: запрос на создание/обновление одной сущности не должен содержать массив*
+ **Описание**: При обновлении отдельной сущности подразумевается, что в теле запроса будет передано её новое представление (одно). В теле запроса должен быть один корневой объект.

<h3><a name="обработка-ошибок-2010"></a>2010</h3>
+ **Сообщение**: *Ошибка формата: отсутствует href для meta поля '{доп. сообщение}'*
+ **Описание**: В переданном объекте метаданных отсутствует поле **href**. Проверьте тело запроса.

<h3><a name="обработка-ошибок-2011"></a>2011</h3>
+ **Сообщение**: *Ошибка формата: отсутствует type для meta поля '{доп. сообщение}'*
+ **Описание**: В переданном объекте метаданных отсутствует поле **type**. Проверьте тело запроса.

<h3><a name="обработка-ошибок-2012"></a>2012</h3>
+ **Сообщение**: *Ошибка формата: неизвестный type для meta поля '{доп. сообщение}'*
+ **Описание**: В переданном объекте метаданных указан неизвестный тип. Проверьте тело запроса. Возможно вы указываете неверное ключевое слово для сущности. Проверьте документацию по данной сущности и убедитесь в правильности передаваемого **type**.

<h3><a name="обработка-ошибок-2013"></a>2013</h3>
+ **Сообщение**: *Ошибка формата: неправильное значение href для meta поля '{доп. сообщение}'*
+ **Описание**: Переданный **href** указывает на несуществующий объект. Убедитесь в корректности ссылки. Ошибка может быть в версии API, типе ресурса (entity/pos/report), ключевом слове сущности/(отчёта), id сущности.

<h3><a name="обработка-ошибок-2014"></a>2014</h3>
+ **Сообщение**: *Ошибка формата: отсутствует meta для поля '{имя поля}'*
+ **Описание**: Для полей типа метаданных (ссылок на другие связанные объекты) необходимо значение в виде объекта, содержащего **meta**.

<h3><a name="обработка-ошибок-2015"></a>2015</h3>
+ **Сообщение**: *Ошибка формата: отсутствует id для поля '{имя поля}'*
+ **Описание**: При передаче вложенных сущностей в виде полей необходимо указывать id этих сущностей.

<h3><a name="обработка-ошибок-2016"></a>2016</h3>
+ **Сообщение**: *Ошибка формата: значение поля '{имя поля}' не соответствует типу {тип поля}*
+ **Описание**: Для указанного поле передано значение неверного типа. Исправьте тело запроса.

<h3><a name="обработка-ошибок-2017"></a>2017</h3>
+ **Сообщение**: *Ошибка формата: неизвестная ошибка*
+ **Описание**: Не удалось однозначно классифицировать ошибку. Убедитесь что формат передаваемых вами данных соответствует требуемому. Посмотрите примеры запросов в документации по используемой вами сущности.

<h3><a name="обработка-ошибок-2018"></a>2018</h3>
+ **Сообщение**: *Ошибка формата: отсутствует поле <field> для meta <type>*
+ **Описание**: Вы не указали обязательное поле объекта **meta**.

<h3><a name="обработка-ошибок-2021"></a>2021</h3>
+ **Сообщение**: *Ошибка формата: в объектах типа '<тип>' полю '<наименование поля>' не может быть присвоен объект типа <тип объекта>*
+ **Описание**: Для сущностей данного типа у указанного поля не может быть выставлено указанное значение. Например, нельзя полю agent отгрузки выставить значение типа employee, тогда как
тому же полю входящего платежа можно выставить значение типа employee.

<h3><a name="обработка-ошибок-2022"></a>2022</h3>
+ **Сообщение**: *Ошибка формата: слишком большое число элементов вложенной коллекции*
+ **Описание**: Вложенная коллекция может иметь в составе не более 100 элементов.

<h3><a name="обработка-ошибок-2024"></a>2024</h3>
+ **Сообщение**: *Ошибка формата: href указывает на сущность неправильного типа '<тип>', требуется '<тип>'*
+ **Описание**: Переданная ссылка href указывает на сущность неправильного типа.

<h3><a name="обработка-ошибок-2025"></a>2025</h3>
+ **Сообщение**: *Ошибка формата: Ошибка формата: значение <заголовок|параметр|поле> '<наименование>' не соответствует формату даты '<формат даты>'*
+ **Описание**: Переданное значение даты не соответствует формату даты

<h2>Общие ошибки валидации</h2>
<h3><a name="обработка-ошибок-3000"></a>3000</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не может быть пустым или отсутствовать*
+ **Описание**: Необходимое поле не может содержать пустого значения или отсутствовать. Все необходимые поля можно посмотреть в документации по сущности, с которой вы работаете, под заголовком "Атрибуты сущности". Такие поля помечены как `Необходимое`.

<h3><a name="обработка-ошибок-3001"></a>3001</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не может быть изменено*
+ **Описание**: Вы пытаетесь изменить поле являющееся полем только для чтения. Все read-only поля можно посмотреть в документации по сущности, с которой вы работаете, под заголовком "Атрибуты сущности". Такие поля помечены как `Только для чтения`.

<h3><a name="обработка-ошибок-3002"></a>3002</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не может иметь отрицательное значение*
+ **Описание**: Данное поле принимает только числовые значения больше либо равные нулю.

<h3><a name="обработка-ошибок-3003"></a>3003</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' должно быть больше нуля*
+ **Описание**: Данное поле принимает только числовые значения больше нуля.
Эта ошибка также возвращается при указании значений, которые при
округлении до 4-го знака после запятой будут равны нулю (т.е. для значений < 0.00005).

<h3><a name="обработка-ошибок-3004"></a>3004</h3>
+ **Сообщение**: *Ошибка сохранения объекта: поле '{имя поля}' не соответствует полю связанного объекта*
+ **Описание**: Поле возврата не соответствует полю документа-основания. Невозможно изменить значения полей `agent, currency, vatIncluded` в возвратах на несоответствующие значениям этих же полей в документе-основании.

<h3><a name="обработка-ошибок-3005"></a>3005</h3>
+ **Сообщение**: *Ошибка сохранения объекта: неверное значение '{значение}' поля '{имя поля}'. Допустимые значения: {список значений}*
+ **Описание**: Вы пытаетесь присвоить несуществующее значение полю типа "перечисление"(enum). Проверить все возможные значения этого поля вы можете в документации по данной сущности в разделе "Атрибуты сущности".

<h3><a name="обработка-ошибок-3006"></a>3006</h3>
+ **Сообщение**: *Ошибка сохранения объекта: нарушено ограничение уникальности параметра '{имя параметра}'*
+ **Описание**: У указанного поля/параметра должно быть уникальное значение в системе. Например, если включена проверка на уникальность номеров операций, `name` у разных документов не может быть одинаковым.

<h3><a name="обработка-ошибок-3007"></a>3007</h3>
+ **Сообщение**: *Ошибка валидации сохраняемого объекта: '{объект}'*
+ **Описание**: Ошибка при обмене. Проверьте, соблюдает ли все условия передаваемый вами объект.

<h3><a name="обработка-ошибок-3008"></a>3008</h3>
+ **Сообщение**: *Ошибка сохранения объекта: значение поля '{имя поля}' превышает максимально допустимое значение*
+ **Описание**: Значение числового поля превышает максимально допустимое значение: 9 999 999 999.

<h3><a name="обработка-ошибок-3009"></a>3009</h3>
+ **Сообщение**: *Ошибка валидации: поле '{имя поля}' не может быть пустым или отсутствовать*
+ **Описание**: Необходимое поле не может содержать пустого значения или отсутствовать.

<h3><a name="обработка-ошибок-3011"></a>3011</h3>
+ **Сообщение**: *Ошибка валидации штрихкода: невозможно добавить к сущности штрихкод длиной более 255 символов*
+ **Описание**: Исправьте длину штрихкода и попробуйте повторить запрос.

<h3><a name="обработка-ошибок-3012"></a>3012</h3>
+ **Сообщение**: *Ошибка валидации: для поля '{имя поля}' массив элементов не должен содержать атомарный тип или null*
+ **Описание**: Нельзя передавать атомарный тип или null в составе массива.

<h3><a name="обработка-ошибок-3013"></a>3013</h3>
+ **Сообщение**: *Ошибка валидации: для поля '{имя поля}' массив элементов не должен содержать сущности с одинаковыми идентификаторами*
+ **Описание**: Нельзя передавать сущности с одинаковыми идентификаторами в составе массива.

<h2>Точки продаж</h2>
<h3><a name="обработка-ошибок-4000"></a>4000</h3>
+ **Сообщение**: *Указанная точка продаж не активна*
+ **Описание**: Для выполнения операции необходимо активировать точку продаж.

<h2>Отчёты комиссионера</h2>
<h3><a name="обработка-ошибок-5000"></a>5000</h3>
+ **Сообщение**: *Неверный тип договора для отчёта комиссионера. Могут быть использованы только договоры типа 'Договор комиссии'(Comission).*
+ **Описание**: При создании / обновлении отчёта комиссионера обязательно указывать договор, который принадлежащит указанному контрагенту и имеет тип 'Договор комиссии'.

<h3><a name="обработка-ошибок-5001"></a>5001</h3>
+ **Сообщение**: *Неверно указан период отчёта комиссионера: конец периода не может быть раньше начала.*
+ **Описание**: Проверьте указанные даты. Дата в поле **commissionPeriodStart** должна быть раньше даты в поле **commissionPeriodEnd**.

<h3><a name="обработка-ошибок-5002"></a>5002</h3>
+ **Сообщение**: *Указанный договор заключен с контрагентом, отличным от указанного в поле agent*
+ **Описание**: При создании / обновлении отчёта комиссионера обязательно указывать договор, который принадлежащит указанному контрагенту и имеет тип 'Договор комиссии'.

<h3><a name="обработка-ошибок-5003"></a>5003</h3>
+ **Сообщение**: *Указанный договор заключен с юрлицом, отличным от указанного в поле organization*
+ **Описание**: Организация должна соответствовать организации, указанной в договоре.

<h2>Характеристики модификаций</h2>
<h3><a name="обработка-ошибок-10000"></a>10000</h3>
+ **Сообщение**: *Ошибка сохранения характеристики модификации: поля 'id' и 'name' не могут быть пустыми*
+ **Описание**: При обновлении характеристик модификации необходимо указывать вышеуказанные поля. Исправьте тело запроса.

<h3><a name="обработка-ошибок-10001"></a>10001</h3>
+ **Сообщение**: *Ошибка сохранения характеристики модификации: поле 'id' ссылается на несуществующую характеристику*
+ **Описание**: По переданному id не удалось найти соответствующую характеристику. Убедитесь в правильности id и повторите запрос.

<h2>Статусы</h2>
<h3><a name="обработка-ошибок-11000"></a>11000</h3>
+ **Сообщение**: *Ошибка инициализации статуса: отсутствует информация о родительской сущности*
+ **Описание**: Не удалось найти документ, к которому должен быть привязан данный статус. Проверьте id документа, а также, в случае обновления, убедитесь, что документ с данным id не был удалён.

<h3><a name="обработка-ошибок-11001"></a>11001</h3>
+ **Сообщение**: *Ошибка инициализации статуса: статус с именем '{Наименование статуса}' не найден*
+ **Описание**: Проверьте в метаданных сущностей данного типа, что статус с передаваемым именем существует, и исправьте запрос.

<h2>Розничные смены (POS)</h2>
<h3><a name="обработка-ошибок-12000"></a>12000</h3>
+ **Сообщение**: *Ошибка открытия розничной смены: розничная смена находится в корзине*
+ **Описание**: Данный **syncId** уже был использован для открытия другой смены. Данная смена уже была удалена. Для открытия новой смены сгенерируйте новый **syncId**.

<h3><a name="обработка-ошибок-12001"></a>12001</h3>
+ **Сообщение**: *Ошибка открытия розничной смены: розничная смена закрыта*
+ **Описание**: Данный **syncId** уже был использован для открытия другой смены. Данная смена уже была закрыта. Переоткрыть её невозможно. Для открытия новой смены сгенерируйте новый **syncId**.

<h3><a name="обработка-ошибок-12002"></a>12002</h3>
+ **Сообщение**: *Ошибка закрытия розничной смены: розничная смена удалена*
+ **Описание**: По переданному id смены не было найдено соответствующего объекта. Смена с данным id либо не существовала, либо была удалена. Проверьте правильность переданного id смены.

<h3><a name="обработка-ошибок-12003"></a>12003</h3>
+ **Сообщение**: *Ошибка закрытия розничной смены: розничная смена находится в корзине*
+ **Описание**: Смена с указанным id находится в корзине. Проверьте правильность указанного вами id смены.

<h3><a name="обработка-ошибок-12004"></a>12004</h3>
+ **Сообщение**: *Ошибка закрытия розничной смены: розничная смена закрыта*
+ **Описание**: Смена с указанным id находится уже была закрыта. Повторное закрытие смены невозможно. Проверьте правильность указанного вами id смены.

<h3><a name="обработка-ошибок-12005"></a>12005</h3>
+ **Сообщение**: *Ошибка открытия розничной смены: не найдена точка продаж*
+ **Описание**: При открытии смены не была найдена точка продаж с указанным id. Проверьте id точки продаж, на которой должна быть открыта новая смена.

<h3><a name="обработка-ошибок-12006"></a>12006</h3>
+ **Сообщение**: *Ошибка открытия розничной смены: параметр 'retailShift' отсутствует или имеет неверный формат*
+ **Описание**: Убедитесь в наличии параметра 'retailShift'.

<h2>Отчёт Остатки</h2>
<h3><a name="обработка-ошибок-13000"></a>13000</h3>
+ **Сообщение**: *Пустой идентификатор операции*
+ **Описание**: Вы запросили отчёт Остатки по операции, не указав id операции. Убедитесь что id передаётся в качестве параметра.

<h3><a name="обработка-ошибок-13001"></a>13001</h3>
+ **Сообщение**: *Операция с указанным идентификатором не найдена*
+ **Описание**: Не удалось найти операцию с указанным <i>operation.id</i>. Проверьте передаваемый вами id, а также убедитесь что операция с данным id не была удалена.

<h3><a name="обработка-ошибок-13002"></a>13002</h3>
+ **Сообщение**: *Операция не может быть выполнена для указанного типа '{тип документа}' документа*
+ **Описание**: Отчёт Остатки по операциям доступен только для операций типа `Отгрузка, Розничная продажа, Заказ покупателя`.

<h3><a name="обработка-ошибок-13003"></a>13003</h3>
+ **Сообщение**: *Отсутствует доступ к отчету Остатки*
+ **Описание**: У пользователя отсутствует доступ к отчету Остатки.

<h2>Дополнительные поля</h2>
<h3><a name="обработка-ошибок-14000"></a>14000</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля: поле '{наименование поля}' не относится к реестру '{тип сущности}'*
+ **Описание**: В своём запросе пытаетесь использовать дополнительные поля другого типа сущности. Сделайте запрос метаданных по данному типу сущности и используйте дополнительные поля которые придут в ответ
<h3><a name="обработка-ошибок-14001"></a>14001</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля: обновление дополнительных полей типа 'Файл' не поддерживается*
+ **Описание**: Поле типа файл обновить нельзя.

<h3><a name="обработка-ошибок-14002"></a>14002</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля: родительская сущность не поддерживает дополнительные поля*
+ **Описание**: Сущности данного типа не могут иметь дополнительных полей. Уточнить список типов сущностей, которые могут иметь дополнительного поля можно в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями)

<h3><a name="обработка-ошибок-14003"></a>14003</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля: идентификатор метаданных указывает на несуществующий объект*
+ **Описание**: Не удалось найти доп поле с указанным id. Проверьте список доп полей и их id с помощью ресурса метаданных сущности.

<h3><a name="обработка-ошибок-14004"></a>14004</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля: для объекта типа 'пользовательский справочник' необходимо указать поле meta или name*
+ **Описание**: Хотя бы одно из вышеуказанных полей не должно быть пустым.

<h3><a name="обработка-ошибок-14005"></a>14005</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля типа 'Файл': размер файла превышает максимально допустимый (10 мб)*
+ **Описание**: Невозможно загрузить в качестве значения дополнительного поля файл размером более 10 мб.

<h3><a name="обработка-ошибок-14006"></a>14006</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля типа 'Файл': отсутствует имя файла*
+ **Описание**: Поле **filename** у значения дополнительного поля типа Файл должно быть заполнено.

<h3><a name="обработка-ошибок-14007"></a>14007</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля типа 'Файл': отсутствует поле content*
+ **Описание**: Поле **content** у значения дополнительного поля типа Файл должно быть заполнено.

<h3><a name="обработка-ошибок-14008"></a>14008</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля типа 'Файл': недостаточно места в хранилище для сохранения файла*
+ **Описание**: Место в хранилище, выделенное для вашего аккаунта, закончилось.

<h3><a name="обработка-ошибок-14009"></a>14009</h3>
+ **Сообщение**: *Ошибка сохранения дополнительного поля типа '{наименование типа поля}': отсутствует поле value*
+ **Описание**: Поле **value** у значения дополнительного поля типа '{наименование типа поля}' должно быть заполнено.

<h3><a name="обработка-ошибок-14010"></a>14010</h3>
+ **Сообщение**: *Доступ запрещён: создавать, изменять и удалять дополнительные поля может только пользователь с правами администратора*
+ **Описание**: создавать, изменять и удалять дополнительные поля может только пользователь с правами администратора.

<h3><a name="обработка-ошибок-14011"></a>14011</h3>
+ **Сообщение**: *Ошибка удаления дополнительного поля: неверный формат meta удаляемого дополнительного поля*
+ **Описание**: По переданной meta не удалось идентифицировать дополнительное поле для удаления.

<h2>Модификации</h2>
<h3><a name="обработка-ошибок-15000"></a>15000</h3>
+ **Сообщение**: *Ошибка сохранения модификации: модификация с данным набором характеристик уже существует для данного товара*
+ **Описание**: Невозможно иметь 2 модификации товара, у которых наборы значений характеристик будут совпадать. Убедитесь что это условие не нарушается. Иначе: используйте уже существующую модификацию.

<h3><a name="обработка-ошибок-15001"></a>15001</h3>
+ **Сообщение**: *Ошибка сохранения модификации: должны быть заданы характеристики*
+ **Описание**: При создании/обновлении модификации переданный массив характеристик не может отсутствовать или быть пустым.

<h3><a name="обработка-ошибок-15002"></a>15002</h3>
+ **Сообщение**: *Ошибка сохранения модификации: нельзя создать модификацию услуги*
+ **Описание**: Поддерживаются только модификации товаров. Убедитесь в правильности URI по которому происходит запрос.

<h3><a name="обработка-ошибок-15003"></a>15003</h3>
+ **Сообщение**: *Ошибка сохранения модификации: нельзя создать модификацию алкогольного товара*
+ **Описание**: Поддерживаются только модификации обычных товаров. Убедитесь в правильности URI по которому происходит запрос.

<h2>Товары</h2>
<h3><a name="обработка-ошибок-16000"></a>16000</h3>
+ **Сообщение**: *Ошибка сохранения товара: свойства алкогольной продукции не могут быть отрицательными*
+ **Описание**: Алкогольные поля "код алкогольной продукции", "крепость" и "объём" должны принимать значение строго большее 0.

<h3><a name="обработка-ошибок-16001"></a>16001</h3>
+ **Сообщение**: *Ошибка сохранения товара: весовой товар не может использовать учет по серийным номерам*
+ **Описание**: Товар не может одновременно быть весовым и использовать учёт по серийным номерам. Это - взаимоисключающие признаки.

<h3><a name="обработка-ошибок-16002"></a>16002</h3>
+ **Сообщение**: *Ошибка сохранения товара: нельзя отключить серийный учёт*
+ **Описание**: Если серийный учет однажды включен, то его уже нельзя отключить. В ином случае вы можете создать новый товар.

<h3><a name="обработка-ошибок-16003"></a>16003</h3>
+ **Сообщение**: *Ошибка сохранения товара: у изображения отсутствует контент*
+ **Описание**: При передаче изображение в составе товара в запросе на создание товара необходимо указывать поле **content**

<h3><a name="обработка-ошибок-16004"></a>16004</h3>
+ **Сообщение**: *Ошибка сохранения товара: невозможно преобразовать поле content в изображение*
+ **Описание**: Содержимым поля "content" должно быть изображение закодированное в формате base64 с расширением jpg или png.

<h3><a name="обработка-ошибок-16005"></a>16005</h3>
+ **Сообщение**: *Ошибка сохранения товара: Недостаточно места в хранилище.*
+ **Описание**: Место в хранилище, выделенное для вашей учётной записи закончилось.

<h3><a name="обработка-ошибок-16006"></a>16006</h3>
+ **Сообщение**: *Ошибка сохранения товара: размер изображения превышает максимально допустимый(3 мб)*
+ **Описание**: Попробуйте уменьшить размер изображения.

<h3><a name="обработка-ошибок-16007"></a>16007</h3>
+ **Сообщение**: *Ошибка сохранения товара: у изображения отсутствует имя файла*
+ **Описание**: При загрузке изображения необходимо указать непустое имя файла в поле **filename**.

<h3><a name="обработка-ошибок-16008"></a>16008</h3>
+ **Сообщение**: *Ошибка сохранения товара: для использования упаковок нужно указать единицу измерения товара*
+ **Описание**: Для использования упаковок должна быть задана единица измерения товара

<h3><a name="обработка-ошибок-16102"></a>16102</h3>
+ **Сообщение**: *Ошибка сохранения товара: товар с типом маркировки «{тип маркировки}» не может иметь модификаций.*
+ **Описание**: У маркированного товара типа "{тип маркировки}" не может быть модификаций

<h3><a name="обработка-ошибок-16103"></a>16103</h3>
+ **Сообщение**: *Ошибка сохранения товара: маркированный товар не может учитываться по серийным номерам.*
+ **Описание**: Товар не может быть одновременно маркированным и учитываться по серийным номерам

<h3><a name="обработка-ошибок-16104"></a>16104</h3>
+ **Сообщение**: *Ошибка сохранения товара: маркированный товар не может быть алкогольным.*
+ **Описание**: Товар не может быть одновременно маркированным и алкогольным

<h3><a name="обработка-ошибок-16105"></a>16105</h3>
+ **Сообщение**: *Ошибка сохранения товара: маркированный товар не может быть весовым.*
+ **Описание**: Товар не может быть одновременно маркированным и весовым

<h3><a name="обработка-ошибок-16106"></a>16106</h3>
+ **Сообщение**: *Ошибка сохранения товара: неизвестный тип маркировки товара.*
+ **Описание**: Тип маркировки товара может быть только одним из следующих: NOT_TRACKED, TOBACCO, SHOES, LP_CLOTHES, LP_LINENS, PERFUMERY, ELECTRONICS, TIRES, MILK, OTP


<h3><a name="обработка-ошибок-16107"></a>16107</h3>
+ **Сообщение**: *Ошибка сохранения товара: поле ТН ВЭД не может быть указано для: «Табачная продукция».*
+ **Описание**: У табачной продукции не может быть кода ТН ВЭД

<h3><a name="обработка-ошибок-16108"></a>16108</h3>
+ **Сообщение**: *Ошибка сохранения товара: значение поля ТН ВЭД не найдено в справочнике.*
+ **Описание**: Указанный код ТН ВЭД не существует в классификаторе ТН ВЭД ЕАЭС

<h3><a name="обработка-ошибок-16109"></a>16109</h3>
+ **Сообщение**: *Ошибка сохранения товара: поле ТН ВЭД не может быть указано для немаркированной продукции.*
+ **Описание**: Поле ТН ВЭД может присутствовать только у маркированных товаров

<h3><a name="обработка-ошибок-16110"></a>16110</h3>
+ **Сообщение**: *Ошибка сохранения товара: <Текст ошибки>*
+ **Описание**: Произошла ошибка сохранения маркированного товара

<h3><a name="обработка-ошибок-16111"></a>16111</h3>
+ **Сообщение**: Ошибка сохранения товара: значение поля ТН ВЭД не соответствует типу маркированной продукции
+ **Описание**: Тип маркированной продукции определенный по ТН ВЭД не соответсвует выбранному пользователем

<h2>Документы</h2>
<h3><a name="обработка-ошибок-17000"></a>17000</h3>
+ **Сообщение**: *Ошибка сохранения документа: счет организации не принадлежит указанной организации*
+ **Описание**: Убедитесь что вы указываете подходящий счёт. Если вы обновляете поле **organization** вместе с ним также должно обновляться поле **organizationAccount**.

<h3><a name="обработка-ошибок-17001"></a>17001</h3>
+ **Сообщение**: *Ошибка сохранения документа: счет контрагента не принадлежит указанному контрагенту*
+ **Описание**: Убедитесь что вы указываете подходящий счёт. Если вы обновляете поле **agent** вместе с ним также должно обновляться поле **agentAccount**.

<h3><a name="обработка-ошибок-17002"></a>17002</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: серийный номер не может быть пустым*
+ **Описание**: Серийный номер не может быть пустой строкой.

<h3><a name="обработка-ошибок-17003"></a>17003</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: количество зарезервированных товаров не может превышать общее количество*
+ **Описание**: Количество зарезервированного товара позиции документа не может превышать общее количество товара по документу.

<h3><a name="обработка-ошибок-17004"></a>17004</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: количество товаров в ожидании не может превышать общее количество*
+ **Описание**: Количество ожидаемого товара позиции документа не может превышать общее количество товара по документу.

<h3><a name="обработка-ошибок-17005"></a>17005</h3>
+ **Сообщение**: *Ошибка сохранения связанного документа: отсутствует ссылка на документ-основание*
+ **Описание**: При сохранении связанного документа необходима ссылка на документ-основание (например при сохранении возврата необходима ссылка на продажу).

<h3><a name="обработка-ошибок-17006"></a>17006</h3>
+ **Сообщение**: *Ошибка сохранения связанного документа: несовместимые типы документов - '<тип1>' и '<тип2>'*
+ **Описание**: В качестве связи вы указали документ несоответствующего типа.

<h3><a name="обработка-ошибок-17007"></a>17007</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: НДС не может быть больше 100*
+ **Описание**: Процент НДС может принимать значения от 0 до 100.

<h3><a name="обработка-ошибок-17008"></a>17008</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: скидка не может быть больше 100*
+ **Описание**: Процент скидки может принимать значения от 0 до 100.

<h3><a name="обработка-ошибок-17009"></a>17009</h3>
+ **Сообщение**: *Ошибка сохранения документа: дата '{тип документа}' не попадает в открытый для редактирования период*
+ **Описание**: Данный документ относится к закрытому периоду. Редактирование документа невозможно.

<h3><a name="обработка-ошибок-17010"></a>17010</h3>
+ **Сообщение**: *Ошибка сохранения документа: вы не можете проводить документы со складом-приемником из другого отдела*
+ **Описание**: В метаданных документа запрещено проводить документы со складом-приемником из другого отдела.

<h3><a name="обработка-ошибок-17011"></a>17011</h3>
+ **Сообщение**: *Ошибка сохранения документа: вы не можете проводить документы со складом-источником из другого отдела*
+ **Описание**: В метаданных документа запрещено проводить документы со складом-источником из другого отдела.

<h3><a name="обработка-ошибок-17012"></a>17012</h3>
+ **Сообщение**: *Ошибка сохранения документа: вы не можете сохранять документы со складом-приемником из другого отдела*
+ **Описание**: В метаданных документа запрещено сохранять документы со складом-приемником из другого отдела.

<h3><a name="обработка-ошибок-17013"></a>17013</h3>
+ **Сообщение**: *Ошибка сохранения документа: вы не можете сохранять документы со складом-источником из другого отдела*
+ **Описание**: В метаданных документа запрещено сохранять документы со складом-источником из другого отдела.

<h3><a name="обработка-ошибок-17014"></a>17014</h3>
+ **Сообщение**: *Ошибка сохранения документа: вы не можете снять проведение у документа типа <тип>, по которому был проведен возврат*
+ **Описание**: Нельзя снять проведение у данного документа, поскольку для него уже был проведен возврат.


<h3><a name="обработка-ошибок-17016"></a>17016</h3>
+ **Сообщение**: *Ошибка сохранения документа: комплект не может быть в составе позиции документа типа {тип_документа}*
+ **Описание**: Комплект не может быть позицией в следующих документах: заказ поставщику, счет поставщика, приемка, возврат поставщику, выданный отчет комиссионера, полученный отчет комиссионера, списание, оприходование, перемещение, инвентаризация, тех. карта, тех. операция, внутренний заказ.

<h3><a name="обработка-ошибок-17018"></a>17018</h3>
+ **Сообщение**: *Ошибка сохранения документа: количество комплектов должно быть целым числом*
+ **Описание**: Количество комплектов в позиции должно быть целым числом

<h3><a name="обработка-ошибок-17020"></a>17020</h3>
+ **Сообщение**: *Ошибка сохранения позиции документа: товар упаковки и товар позиции отличаются*
+ **Описание**: Для данной позиции документа товар из упаковки и указанный товар отличаются

<h3><a name="обработка-ошибок-17101"></a>17101</h3>
+ **Сообщение**: *Ошибка сохранения документа: для товара <наименование товара> не установлен признак маркированной продукции. Измените товар для сохранения кодов маркировки*
+ **Описание**: Установите для товара признак маркированной продукции 'trackingType' соответствующей категории

<h3><a name="обработка-ошибок-17102"></a>17102</h3>
+ **Сообщение**: *Ошибка сохранения документа: неверный формат кода маркировки <значение КМ / КМ ТУ / КМ ПУ>*
+ **Описание**:

Код маркировки для всех категорий маркированной продукции должен соответствовать формату:
  + 01+GTIN+21+SERIAL. GTIN - идентификатор товара из 14 цифр, SERIAL - серийный номер из 13 символов. Пример:
<b><font color='green'>01</font>04630037590265<font color='green'>21</font>K6UT)6\\"pIG-<</b>

Исключения:
  + Табачная продукция продукция, пачка: GTIN+SERIAL. GTIN - идентификатор товара из 14 цифр, SERIAL - серийный номер из 7 символов.
  + Табачная продукция продукция, блок (упаковка): 01+GTIN+21+SERIAL. GTIN - идентификатор товара из 14 цифр, SERIAL - серийный номер из 7 символов. Пример:
<b>01</b>04630034070029<b>21</b>tXXXu%d
  + Фотокамеры и лампы-вспышки:01+GTIN+21+SERIAL. GTIN - идентификатор товара из 14 цифр, SERIAL - серийный номер из 20 символов.
  + Код маркировки транспортной упаковки продукции должен содержать 18 цифр - формат GS1.

<h3><a name="обработка-ошибок-17103"></a>17103</h3>
+ **Сообщение**: *Ошибка сохранения документа: в документе несколько одинаковых кодов <значение КМ / КМ ТУ / КМ ПУ>*
+ **Описание**: Среди кодов маркировки есть дублирующиеся. Удалите дубликаты кодов маркировки для сохранения позиции

<h3><a name="обработка-ошибок-17104"></a>17104</h3>
+ **Сообщение**: *Ошибка сохранения документа: код маркировки <КМ> не может содержать вложенные коды*
+ **Описание**: Допустимо сохранять список кодов маркировки <b>trackingcode</b>, список потребительских упаковок <b>consumerpack</b>, список транспортных упаковок <b>transportpack</b>, список кодов маркировки <b>trackingcode</b> вложенных в транспортные упаковки <b>transportpack</b> или потребительские упаковки <b>consumerpack</b>, список потребительских упаковок <b>consumerpack</b> вложенных в транспортные упаковки <b>transportpack</b>. Сохранение других вложенных структур не поддерживается

<h3><a name="обработка-ошибок-17105"></a>17105</h3>
+ **Сообщение**: *Ошибка сохранения документа: код маркировки транспортной упаковки <КМ ТУ> не может содержать вложенные коды транспортных упаковок*
+ **Описание**: Допустимо сохранять список кодов маркировки <b>trackingcode</b> и список потребительских упаковок <b>consumerpack</b> вложенных в транспортные упаковки <b>transportpack</b>. Не поддерживается сохранение транспортных упаковок вложенных в транспортные упаковки

<h3><a name="обработка-ошибок-17106"></a>17106</h3>
+ **Сообщение**: *Ошибка сохранения документа: код маркировки потребительской упаковки не может содержать вложенные коды*
+ **Описание**: Допустимо сохранять список кодов маркировки <b>trackingcode</b> вложенных в транспортные упаковки <b>transportpack</b>. Не поддерживается сохранение кодов маркировки <b>trackingcode</b> вложенных в потребительские упаковки <b>consumerpack</b>

<h3><a name="обработка-ошибок-17107"></a>17107</h3>
+ **Сообщение**: *Ошибка сохранения документа: код маркировки транспортной упаковки <КМ ТУ> не может одновременно содержать вложенные коды товаров и потребительских упаковок*
+ **Описание**: Допустимо сохранять список кодов маркировки <b>trackingcode</b> или список потребительских упаковок <b>consumerpack</b> вложенных в транспортные упаковки <b>transportpack</b>. Не поддерживается их одновременное сохранение для одной транспортной упаковки

<h2>Продажи/Отгрузки</h2>
<h3><a name="обработка-ошибок-18000"></a>18000</h3>
+ **Сообщение**: *Ошибка сохранения продажи: сумма 'cashSum', 'noCashSum', 'prepaymentCashSum' и 'prepaymentNoCashSum' не соответствует сумме по документу*
+ **Описание**: Сумма полей **cashSum**, **noCashSum**, **prepaymentCashSum** и **prepaymentNoCashSum** должна быть равна значению поля **sum** или отличаться менее чем на 10 единиц. В случае создания документа и указании вышеупомянутых полей в теле запроса, ответственность за подсчёт **sum** ложится на пользователя. **sum** считается как общая сумма по всем позициям документа.

<h3><a name="обработка-ошибок-18002"></a>18002</h3>
+ **Сообщение**: *Ошибка сохранения документа: отгрузка по комиссионному договору не может содержать комплект в составе позиций*
+ **Описание**: В отгрузку нельзя добавить комплект, если для неё указан договор типа "Комиссионный"".

<h2>Возвраты</h2>
<h3><a name="обработка-ошибок-19000"></a>19000</h3>
+ **Сообщение**: *Ошибка сохранения возврата: розничная смена уже закрыта*
+ **Описание**: Нельзя сохранить возврат в закрытую розничную смену. Убедитесь что используете идентификатор активной смены.

<h3><a name="обработка-ошибок-19001"></a>19001</h3>
+ **Сообщение**: *Ошибка сохранения розничного возврата: поля 'cashSum' и 'noCashSum' являются обязательными для возврата без основания*
+ **Описание**: Поля 'cashSum' и 'noCashSum' являются обязательными для возврата без основания. Убедитесь, что они заполнены.

<h3><a name="обработка-ошибок-19002"></a>19002</h3>
+ **Сообщение**: *Ошибка сохранения розничного возврата: сумма 'cashSum' и 'noCashSum' не соответствует сумме по документу*
+ **Описание**: Сумма полей **cashSum** и **noCashSum** должна быть равна значению поля **sum** или отличаться менее чем на 10 единиц. В случае создания документа и указании вышеупомянутых полей в теле запроса, ответственность за подсчёт **sum** ложится на пользователя. **sum** считается как общая сумма по всем позициям документа.

<h2>Приёмки</h2>
<h3><a name="обработка-ошибок-20000"></a>20000</h3>
+ **Сообщение**: *Ошибка сохранения приемки: нельзя указать накладные расходы с договором комиссии*
+ **Описание**: Если к приёмке привязан договор типа "Договор комиссии", то нельзя указать какое-либо значение в поле **overhead**.

<h2>Перемещения</h2>
<h3><a name="обработка-ошибок-21000"></a>21000</h3>
+ **Сообщение**: *Ошибка сохранения перемещения: нельзя провести перемещение со склада на этот же склад*
+ **Описание**: Убедитесь, что в полях **sourceStore** и **targetStore** указываете склады с разными идентификаторами.

<h2>Платежи</h2>
<h3><a name="обработка-ошибок-22000"></a>22000</h3>
+ **Сообщение**: *Ошибка сохранения платежа: распределенная сумма превышает сумму платежа*
+ **Описание**: Сумма, указанная в **linkedSum** больше чем **sum** платежа.

<h3><a name="обработка-ошибок-22001"></a>22001</h3>
+ **Сообщение**: *Ошибка сохранения платежа: платеж содержит повторяющиеся привязанные документы*
+ **Описание**: Вы пытаетесь привязать платеж к документу более одного раза.

<h3><a name="обработка-ошибок-22002"></a>22002</h3>
+ **Сообщение**: *Ошибка сохранения платежа: некорректная статья расходов: '{категория расходов}'*
+ **Описание**: Платежу нельзя присвоить данную статью расходов.

<h2>Группы товаров</h2>
<h3><a name="обработка-ошибок-23000"></a>23000</h3>
+ **Сообщение**: *Ошибка сохранения группы: нельзя указывать в качестве родительской группы саму группу*
+ **Описание**: Группа не может в качестве родительской ссылаться на саму себя.

<h3><a name="обработка-ошибок-23001"></a>23001</h3>
+ **Сообщение**: *Ошибка сохранения группы: нельзя указывать в качестве родительской группы вложенную группу*
+ **Описание**: Группа не может в качестве родительской группы ссылаться на группу, которая является ее дочерней группой.

<h2>Инвентаризация</h2>
<h3><a name="обработка-ошибок-24001"></a>24001</h3>
+ **Сообщение**: *Ошибка создания шаблона списания: инвентаризация не требует проведения списания*
+ **Описание**: Инвентаризация не содержит недостачи, либо все необходимые списания уже созданы.

<h3><a name="обработка-ошибок-24002"></a>24002</h3>
+ **Сообщение**: *Ошибка создания шаблона оприходования: инвентаризация не требует проведения оприходования*
+ **Описание**: Инвентаризация не содержит избытка, либо все необходимые оприходования уже созданы.

<h3><a name="обработка-ошибок-24003"></a>24003</h3>
+ **Сообщение**: *Ошибка сохранения инвентаризации: услуга не может быть позицией инвентаризации*
+ **Описание**: Услуга не может быть позицией инвентаризации.

<h3><a name="обработка-ошибок-24004"></a>24004</h3>
+ **Сообщение**: *Ошибка сохранения инвентаризации: инвентаризация не может содержать дублирующихся позиций*
+ **Описание**: Товар/Услуга/Модификация/Серия/Комплект может быть добавлен(а) в инвентаризацию только единожды.

<h2>Технологические операции</h2>
<h3><a name="обработка-ошибок-25001"></a>25001</h3>
+ **Сообщение**: *Ошибка сохранения технологической операции: позиции операции не соответствуют позициям тех. карты*
+ **Описание**: Проверьте соответствие продуктов и материалов тех. операции и тех. карты.

<h3><a name="обработка-ошибок-25002"></a>25002</h3>
+ **Сообщение**: *Ошибка сохранения технологической операции: состав позиций не может быть изменён*
+ **Описание**: Состав продуктов и материалов тех. операции не может быть изменён.

<h2>Заказы на производство</h2>
<h3><a name="обработка-ошибок-26001"></a>26001</h3>
+ **Сообщение**: *Ошибка сохранения заказа на производство: материалы заказа не соответствуют материалам тех. карты*
+ **Описание**: Проверьте соответствие материалов заказа на производство и тех. карты.

<h3><a name="обработка-ошибок-26002"></a>26002</h3>
+ **Сообщение**: *Ошибка сохранения заказа на производство: новые товары не могут быть добавлены в заказ*
+ **Описание**: Проверьте заказ на наличие новых товаров.

<h2>Прайс-листы</h2>
<h3><a name="обработка-ошибок-27000"></a>27000</h3>
+ **Сообщение**: *Ошибка сохранения описания таблицы, '{описание ошибки}'*
+ **Описание**: На создание таблицы Прайс-листа налагаются следующие ограничения: для описанного столбца не может отсутствовать или быть пустым название, в пределах одного Прайс-листа столбцы должны быть уникальные по названию.

<h3><a name="обработка-ошибок-27001"></a>27001</h3>
+ **Сообщение**: *Ошибка сохранения позиции, для указанного имени столбца не найден столбец в описании таблицы*
+ **Описание**: Значение ячеек в позициях Прайс-листа соотносятся со столбцами по названию. Нельзя указывать для ячейки название несуществующих в определении Прайс-листа столбцов.

<h3><a name="обработка-ошибок-27002"></a>27002</h3>
+ **Сообщение**: *Ошибка сохранения позиции, нельзя в прайс-листе указывать повторяющиеся позиции*
+ **Описание**: Нельзя в прайс-листе указывать повторящиеся позиции, например, товар или его модификацию дважды.

<h3><a name="обработка-ошибок-27003"></a>27003</h3>
+ **Сообщение**: *Ошибка сохранения позиции, нельзя в прайс-листе указывать серии*
+ **Описание**: Нельзя в прайс-листе указывать серии, только товары, услуги и модификации.

<h2>Контрагенты</h2>
<h3><a name="обработка-ошибок-28000"></a>28000</h3>
+ **Сообщение**: *Ошибка сохранения контрагента: неизвестный тип цены: '<Тип цены>'*
+ **Описание**: Неизвестный тип цены. Список допустимых можно запросить в метаданных товаров.

<h2>Комплекты</h2>
<h3><a name="обработка-ошибок-29000"></a>29000</h3>
+ **Сообщение**: *Ошибка сохранения комплекта: некорректное число компонентов*
+ **Описание**: Поддерживается от одного до пятидесяти компонентов в одном комплекте.

<h3><a name="обработка-ошибок-29001"></a>29001</h3>
+ **Сообщение**: *Ошибка сохранения комплекта: дополнительные расходы и состав компонентов не могут быть изменены, так как комплект уже используется*
+ **Описание**: Уберите зависимые комплекты из документов.

<h3><a name="обработка-ошибок-29002"></a>29003</h3>
+ **Сообщение**: *Ошибка сохранения комплекта: комплект содержит повторяющиеся компоненты*
+ **Описание**: Проверьте состав компонентов комплекта и попробуйте снова.

<h3><a name="обработка-ошибок-29003"></a>29004</h3>
+ **Сообщение**: *Ошибка сохранения комплекта: компонент комплекта не может быть комплектом, серией, алкогольным товаром или товаром на серийном учете*
+ **Описание**: Проверьте состав компонентов комплекта и попробуйте снова.

<h2>Веб-хуки</h2>
<h3><a name="обработка-ошибок-30000"></a>30000</h3>
+ **Сообщение**: *Ошибка сохранения webhook: неподдерживаемый тип сущности '{тип}'*
+ **Описание**: В веб-хуках можно использовать любые типы сущностей, доступные через Remap API, кроме вложенных. Например, product или demand.

<h3><a name="обработка-ошибок-30001"></a>30001</h3>
+ **Сообщение**: *Ошибка сохранения webhook: неизвестный HTTP-метод '{метод}'. Допустимый: POST*
+ **Описание**: В веб-хуках можно указывать только поддерживаемые HTTP методы. Допустимым сейчас является POST.

<h3><a name="обработка-ошибок-30002"></a>30002</h3>
+ **Сообщение**: *Ошибка сохранения webhook: неизвестное действие '{действие}'. Допустимые: CREATE, UPDATE, DELETE*
+ **Описание**: В веб-хуках можно указывать только доступные действия: CREATE, UPDATE, DELETE.

<h3><a name="обработка-ошибок-30003"></a>30003</h3>
+ **Сообщение**: *Ошибка сохранения webhook: webhook с данным набором параметров уже существует*
+ **Описание**: В веб-хуках на пару (сущность, действие) может быть установлен только один веб-хук.

<h3><a name="обработка-ошибок-30004"></a>30004</h3>
+ **Сообщение**: *Необходимы права администратора для работы с webhook*
+ **Описание**: Управление веб-хуками доступно только пользователям с правами администратора.

<h3><a name="обработка-ошибок-30005"></a>30005</h3>
+ **Сообщение**: *Ошибка сохранения webhook: значение поля url не является корректным адресом запроса*
+ **Описание**: Значение поля url не является корректным адресом запроса. Проверьте адрес запроса на соответствие формату http, https адреса запроса.

<h3><a name="обработка-ошибок-30006"></a>30006</h3>
+ **Сообщение**: *Ваш тарифный план не позволяет создавать или обновлять веб-хуки*
+ **Описание**: Создание и обновление веб-хуков доступно на всех тарифах кроме бесплатного.

<h2>Валюты</h2>
<h3><a name="обработка-ошибок-31000"></a>31000</h3>
+ **Сообщение**: *Валюту учета нельзя удалить*
+ **Описание**: Валюту учета нельзя удалить.

<h2>Договоры</h2>
<h3><a name="обработка-ошибок-32001"></a>32001</h3>
+ **Сообщение**: *Ошибка сохранения договора: невозможно изменить тип договора на комиссионный. По данному договору существует отгрузка, в составе позиций которой присутствует комплект*
+ **Описание**: Проверьте, чтобы по данному договору не было отгрузок комплектов и попробуйте снова.

<h3><a name="обработка-ошибок-32002"></a>32002</h3>
+ **Сообщение**: *Ошибка сохранения договора: невозможно изменить тип договора на комиссионный. Договор, используемый в документах с компонентами комплектов, не может быть комиссионным*
+ **Описание**: Проверьте, чтобы по данному договору не было документов с компонентами комплектов и попробуйте снова.

<h2>Печатные формы<h2>
<h3><a name="обработка-ошибок-33000"></a>33000</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: не найден шаблон печатной формы*
+ **Описание**: Шаблон, указанный при формировании печатной формы не существует. Проверьте корректность указанного шаблона для печати.

<h3><a name="обработка-ошибок-33001"></a>33001</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: неизвестный формат*
+ **Описание**: Проверьте, что указанный формат входит в список перечисленных: xls, pdf, html, ods.

<h3><a name="обработка-ошибок-33002"></a>33002</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: '<текст ошибки>'*
+ **Описание**: Текст ошибки указывает на проблемы, возникшие при печати документа.

<h3><a name="обработка-ошибок-33003"></a>33003</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: отсутствует ссылка на шаблон для печати*
+ **Описание**: Для того, чтобы сгенерировать печатную форму, необходимо отправить шаблон.

<h3><a name="обработка-ошибок-33004"></a>33004</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: отсутствует поле count для шаблона печатной формы*
+ **Описание**: При печати комплектов необходимо указывать поле **count** - число копий печатной формы в комплекте.

<h3><a name="обработка-ошибок-33005"></a>33005</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: указаны оба поля для ссылок на шаблон: template и templates.*
+ **Описание**: Возможно указать только одно из полей запроса **template** или **templates**.

<h3><a name="обработка-ошибок-33006"></a>33006</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: поле count для шаблона печатной формы может принимать только целые значения в диапазоне от 1 до 10*
+ **Описание**: Поле **count** должно быть в интервале [1, 10].

<h3><a name="обработка-ошибок-33007"></a>33007</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: отсутствует ссылка на юрлицо*
+ **Описание**: Для того, чтобы сгенерировать печатную форму для товара, необходимо отправить ссылку на юрлицо.

<h3><a name="обработка-ошибок-33008"></a>33008</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: отсутствует количество ценников/термоэтикеток*
+ **Описание**: Для того, чтобы сгенерировать печатную форму для товара, необходимо отправить количество.

<h3><a name="обработка-ошибок-33009"></a>33009</h3>
+ **Сообщение**: *Ошибка формирования печатной формы: отсутствует тип цены*
+ **Описание**: Для того, чтобы сгенерировать печатную форму для товара, необходимо отправить тип цены.

<h3><a name="обработка-ошибок-33010"></a>33010</h3>
+ **Сообщение**: *Ошибка формирования печатной формы комплекта документов: для указанной сущности не было передано подходящих шаблонов печатной формы.*
+ **Описание**: Чтобы напечатать комплект документов, нужно передать хотя бы 1 подходящий для данной сущности шаблон печатной формы.

<h3><a name="обработка-ошибок-33011"></a>33011</h3>
+ **Сообщение**: *Ошибка формирования печатной формы комплекта документов: сущность для печати комплекта должна быть документом*
+ **Описание**: Невозможно напечатать комплект документов для сущности, не являющейся документом.

<h3><a name="обработка-ошибок-33012"></a>33012</h3>
+ **Сообщение**: *Печать для типа '{тип}' не поддерживается*
+ **Описание**: Печать не поддерживается для данного типа.

<h2>Публикации<h2>
<h3><a name="обработка-ошибок-34000"></a>34000</h3>
+ **Сообщение**: *Публикации для типа '{тип}' не поддерживаются*
+ **Описание**: Публикации доступны только для следующих типов: Заказ покупателя, Счет покупателю, Отгрузка, Заказ поставщику, Счет поставщика, Приемка, Входящий платеж, Приходный ордер, Исходящий платеж, Расходный ордер, Внутренний заказ, Перемещение, Оприходование, Списание, Счет-фактура выданный, Счет-фактура полученный, Возврат поставщику, Возврат покупателя, Выплата денег, Внесение денег, Розничный возврат, Розничная продажа, Договор.

<h3><a name="обработка-ошибок-34001"></a>34001</h3>
+ **Сообщение**: *Не удалось создать публикацию. Проверьте корректность шаблона.*
+ **Описание**: Во время генерации документа возникла ошибка. Проверьте корректность передаваемого шаблона.

<h3><a name="обработка-ошибок-34002"></a>34002</h3>
+ **Сообщение**: *Ошибка создания публикации документов: ваш тариф не позволяет создавать публикацию документов на основе пользовательского шаблона печатной формы*
+ **Описание**: Ваш тарифный план не позволяет использовать при публикации документов пользовательские шабоны.

<h3><a name="обработка-ошибок-34003"></a>34003</h3>
+ **Сообщение**: *Ошибка: нельзя работать с публикацией сущности так как к ней отсутствует доступ на '<чтение, запись>'.*
+ **Описание**: Работа пользователя с публикациями документов возможна, если есть право на чтение и право печати сущности данного типа.

<h2>Счета-фактуры<h2>
<h3><a name="обработка-ошибок-35000"></a>35000</h3>
+ **Сообщение**: *Ошибка формирования счета-фактуры: передано более 1 документа-основания в коллекции*
+ **Описание**: Счет-фактура может быть создан только на основании одного документа. Проверьте, что был передан один массив связанных документов с одним документом-основанием.

<h3><a name="обработка-ошибок-35001"></a>35001</h3>
+ **Сообщение**: *Ошибка формирования счета-фактуры: документ уже внесен в счет-фактуру*
+ **Описание**: Счет-фактура уже создан на основании переданного документа.

<h2>Шаблоны<h2>
<h3><a name="обработка-ошибок-36000"></a>36000</h3>
+ **Сообщение**: *Ошибка формирования шаблона: передано более 1 документа-основания для формирования шаблона*
+ **Описание**: Не удалось сформировать предзаполненную сущность из-за того что передано более 1 документа-основания.

<h2>Задачи<h2>
<h3><a name="обработка-ошибок-37000"></a>37000</h3>
+ **Сообщение**: *Ошибка: вы не можете работать с задачами, т.к. в вашем тарифном плане отсутствует опция CRM*
+ **Описание**: Вы не можете создавать, редактировать и удалять задачи без тарифной опции CRM.

<h3><a name="обработка-ошибок-37001"></a>37001</h3>
+ **Сообщение**: *Ошибка: вы не можете редактировать или удалить задачу, созданную другим сотрудником*
+ **Описание**: Пользователь, не являющийся администратором, может изменять или удалять только задачи, которые создал он сам, либо менять статус готовности у задачи, на которую он назначен ответственным.

<h3><a name="обработка-ошибок-38000"></a>38000</h3>
+ **Сообщение**: *Необходимы права администратора для работы с аудитом*
+ **Описание**: Просмотр изменений доступен только пользователям с правами администратора.

<h2>Пользовательские справочники<h2>
<h3><a name="обработка-ошибок-41000"></a>41000</h3>
+ **Сообщение**: *Ошибка: пользовательский справочник с идентификатором '{идентификатор}' не найден*
+ **Описание**: Пользовательский справочник с указанным идентификатором не найден

<h3><a name="обработка-ошибок-41001"></a>41001</h3>
+ **Сообщение**: *Ошибка: ваш тариф не позволяет работать с пользовательскими справочниками*
+ **Описание**: Для тарифов "Бесплатный", "Бесплатный 2014" и "Индивидуальный" не поддерживается работа с пользовательскими справочниками.

<h2>Сотрудники</h2>
<h3><a name="обработка-ошибок-43001"></a>43001</h3>
+ **Сообщение**: *Ошибка сохранения сотрудника: у изображения отсутствует контент*
+ **Описание**: При передаче изображения в запросе на изменение сотрудника необходимо указывать поле **content**

<h3><a name="обработка-ошибок-43002"></a>43002</h3>
+ **Сообщение**: *Ошибка сохранения сотрудника: невозможно преобразовать поле content в изображение*
+ **Описание**: Содержимым поля **content** должно быть изображение, закодированное в формате base64 с расширением jpg или png.

<h3><a name="обработка-ошибок-43003"></a>43003</h3>
+ **Сообщение**: *Ошибка сохранения сотрудника: Недостаточно места в хранилище.*
+ **Описание**: Место в хранилище, выделенное для вашей учётной записи закончилось.

<h3><a name="обработка-ошибок-43004"></a>43004</h3>
+ **Сообщение**: *Ошибка сохранения сотрудника: размер изображения превышает максимально допустимый(3 мб)*
+ **Описание**: Попробуйте уменьшить размер изображения.

<h3><a name="обработка-ошибок-43005"></a>43005</h3>
+ **Сообщение**: *Ошибка сохранения сотрудника: у изображения отсутствует имя файла*
+ **Описание**: При загрузке изображения необходимо указать непустое имя файла в поле **filename**.

<h3><a name="обработка-ошибок-43006"></a>43006</h3>
+ **Сообщение**: *Ошибка сохранения сотрудника: неверный формат ИНН*
+ **Описание**: Проверьте, чтобы формат ИНН соответствовал формату ИНН физического лица.

<h2>Скачивание изображений<h2>
<h3><a name="обработка-ошибок-44000"></a>44000</h3>
+ **Сообщение**: *Метод POST не поддерживается для URL '<url>'*
+ **Описание**: HTTP метод POST не поддерживается для запроса на скачивание изображения.

<h3><a name="обработка-ошибок-44001"></a>44001</h3>
+ **Сообщение**: *Метод PUT не поддерживается для URL '<url>'*
+ **Описание**: HTTP метод PUT не поддерживается для запроса на скачивание изображения.

<h3><a name="обработка-ошибок-44002"></a>44002</h3>
+ **Сообщение**: *Метод DELETE не поддерживается для URL'<url>'*
+ **Описание**: HTTP метод DELETE не поддерживается для запроса на скачивание изображения.

<h2>Тарифные ограничения</h2>
<h3><a name="обработка-ошибок-47000"></a>47000</h3>
+ **Сообщение**: *Тарифное ограничение: {описание ограничения}*
+ **Описание**: Сработало тарифное ограничение для текущего тарифа.
