FORMAT: 1A
HOST: https://online.moysklad.ru/api/remap/1.1


# МойСклад JSON API 1.1

<span style="color:red;font-size:14pt">**Данная версия API устарела, она поддерживается и работает, <br /> но в ней не появляются новые возможности**</span>

API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.

<!-- include(general.apib) -->
