#Group Уведомления Типы уведомлений
## Форматы полей
### Формат измененного поля
Формат измененного поля содержит в себе старое и новое значение:
+ **oldValue** - Старое значение
+ **newValue** - Новое значение

Формат oldValue и newValue совпадает с форматом поля, изменение которого отображается. Одно из полей может быть не заполнено.

### Возможные значения типа экспорта
+ **export_csv_good**
+ **export_csv_agent**
+ **export_ms_xml**
+ **export_1c_v2_xml**
+ **export_unisender**
+ **export_1c_v3_xml**
+ **export_subscribepro**
+ **export_1c_client_bank**
+ **export_alfa_payments**
+ **export_tochka_payments**
+ **export_modulbank_payments**
+ **export_1c_enterprise_data**
+ **export_tinkoff_payments**
+ **export_good**
+ **export_custom_entity**

### Возможные значения типа импорта
+ **importer_csv**
+ **importer_yml**
+ **importer_csv_agent**
+ **importer_csv_customerorder**
+ **importer_csv_purchaseorder**
+ **importer_csv_pricelist**
+ **importer_ms_xml**
+ **importer_1c_client_bank**
+ **import_alfa_payments**
+ **import_alfa_payments_request**
+ **import_alfa_payments_save**
+ **import_tochka_payments**
+ **import_modulbank_payments**
+ **import_tochka_payments_save**
+ **import_modulbank_payments_save**
+ **import_tinkoff_payments**
+ **import_tinkoff_payments_save**
+ **importer_good**
+ **importer_good_in_doc**
+ **import_edo_supply**
+ **import_union_company**
+ **import_sberbank_payments_request**
+ **import_sberbank_payments_save**
+ **import_update_vat_to_20_percents**
+ **import_custom_entity**


## Сводная таблица типов уведомлений
  | Тип уведомления                     | Группа                | О чем уведомление                                    |
  |-------------------------------------|:----------------------|:------------------------------|
  | NotificationOrderNew		        | Заказ покупателя		| Новый заказа покупателя |
  | NotificationOrderOverdue		    | Заказ покупателя		| Просрочен заказ |
  | NotificationInvoiceOutOverdue		| Счет		            | Просрочен счёт, который не оплатил или не полностью оплатил покупатель |
  | NotificationGoodCountTooLow		    | Остатки	        	| Снижение количества товара до неснижаемого остатка |
  | NotificationTaskAssigned	    	| Задача	        	| Задача назначена |
  | NotificationTaskUnassigned	    	| Задача		        | Задача снята |
  | NotificationTaskOverdue		        | Задача		        | Задача просрочена |
  | NotificationTaskCompleted	        | Задача		        | Задача выполнена |
  | NotificationTaskReopened	    	| Задача		        | Задача переоткрыта |
  | NotificationTaskNewComment		    | Задача	        	| У задачи появился новый комментарий |
  | NotificationTaskChanged	    	    | Задача	        	| Задача поменялась |
  | NotificationTaskDeleted		        | Задача	        	| Задача удалена |
  | NotificationTaskCommentDeleted	    | Задача	        	| Комментарий у задачи был удален |
  | NotificationTaskCommentChanged	    | Задача	        	| Комментарий у задачи был изменен |
  | NotificationImportCompleted		    | Обмен данными	    	| Импорт выполнен |
  | NotificationExportCompleted		    | Обмен данными	    	| Экспорт выполнен |
  | NotificationSubscribeExpired        | Биллинг               | Окончание подписки |
  | NotificationSubscribeTermsExpired   | Биллинг               | Истекают условия подписки |
  | NotificationRetailShiftOpened       | Розничная торговля    | Открыта смена |
  | NotificationRetailShiftClosed       | Розничная торговля    | Закрыта смена |
  | NotificationScript       | Сценарии    | Уведомление из сценария |

## Подробное описание типов уведомлений [/notification/{id}]

## Завершение экспорта [GET]
<h3> Тип уведомления </h3>
NotificationExportCompleted - завершение экспорта
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **message** - Сообщение о завершении экспорта
+ **errorMessage** - Сообщение об ошибке
+ **createdDocumentName** - Имя экспортированного документа
+ **taskType** - [Тип экспорта](#header-возможные-значения-типа-экспорта) `Необходимое`
+ **taskState** - Статус завершения `Необходимое`. Может принимать значения `completed`, `interrupted`, `interrupted_by_user`, `interrupted_by_timeout`, `interrupted_by_system`
+ Parameters
  + id: `02950e3c-35f2-11e9-9ff4-34e8000799c0` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/export_completed.json) -->

## Завершение импорта [GET]
<h3> Тип уведомления </h3>
NotificationImportCompleted - завершение импорта
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **message** - Сообщение о завершении импорта
+ **errorMessage** - Сообщение об ошибке
+ **createdDocumentName** - Имя документа
+ **taskType** - [Тип импорта](#header-возможные-значения-типа-импорта) `Необходимое`
+ **taskState** - Статус завершения `Необходимое`. Может принимать значения `completed`, `interrupted`, `interrupted_by_user`, `interrupted_by_timeout`, `interrupted_by_system`
+ Parameters
  + id: `02950e31-35f2-11e9-9ff4-34e8000799c0` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/import_completed.json) -->

## Снижение остатка товара ниже неснижаемого [GET]
<h3> Тип уведомления </h3>
NotificationGoodCountTooLow - снижение остатка товара ниже неснижаемого
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **actualBalance** - Остаток товара `Необходимое`
+ **minimumBalance** - Неснижаемый остаток товара `Необходимое`
+ **good** - Ссылка на товар в формате [Метаданных](#header-метаданные) `Необходимое`
+ Parameters
  + id: `9338c8bd-56e5-11e9-c0a8-100b00000023` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/good_count_too_low.json) -->

## Просрочен счет покупателя [GET]
<h3> Тип уведомления </h3>
NotificationInvoiceOutOverdue - просрочен счет покупателя
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **invoice** - Ссылка на счет в формате [Метаданных](#header-метаданные) `Необходимое`
  + **paymentPlannedMoment** - Запланированная дата оплаты
  + **sum** - Сумма счета
  + **agentName** - Имя контрагента
+ Parameters
  + id: `572d1dd9-56fc-11e9-c0a8-100b00000006` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/invoice_out_overdue.json) -->

## Новый заказ [GET]
<h3> Тип уведомления </h3>
NotificationOrderNew - новый заказ
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **order** - Ссылка на заказ в формате [Метаданных](#header-метаданные) `Необходимое`
  + **deliveryPlannedMoment** - Планируемое время отгрузки
  + **sum** - Сумма заказа
  + **agentName** - Имя контрагента
+ Parameters
  + id: `c6082a9e-56e1-11e9-c0a8-100b00000011` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/order_new.json) -->

## Просроченный заказ [GET]
<h3> Тип уведомления </h3>
NotificationOrderOverdue - просроченный заказ
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **order** - Ссылка на заказ в формате [Метаданных](#header-метаданные) `Необходимое`
  + **deliveryPlannedMoment** - Планируемое время отгрузки
  + **sum** - Сумма заказа
  + **agentName** - Имя контрагента
+ Parameters
  + id: `c6082a9e-56e1-11e9-c0a8-100b00000011` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/order_overdue.json) -->


## Окончание подписки [GET]
<h3> Тип уведомления </h3>
NotificationSubscribeExpired - окончание подписки
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ Parameters
  + id: `c2582a9e-56e1-11e9-c0a8-100b00000123` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/subscribe_expired.json) -->

## Условия подписки истекают [GET]
<h3> Тип уведомления </h3>
NotificationSubscribeTermsExpired - условия подписки истекают
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **daysLeft** - Количество оставшихся дней подписки `Необходимое`
+ Parameters
  + id: `c2582a9e-56e1-11e9-c0a8-100b00000125` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/subscribe_terms_expired.json) -->

## Задача назначена [GET]
<h3> Тип уведомления </h3>
NotificationTaskAssigned - задача назначена
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ Parameters
  + id: `bcd815b9-56ca-11e9-c0a8-100b00000001` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_assigned.json) -->

## Задача снята [GET]
<h3> Тип уведомления </h3>
NotificationTaskUnassigned - задача снята
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ Parameters
  + id: `80c8a58b-56cb-11e9-c0a8-100b00000009` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_unassigned.json) -->

## Задача изменена [GET]
<h3> Тип уведомления </h3>
NotificationTaskChanged - задача изменена
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **diff** - Измененные поля `Необходимое`
  + **description** - Изменение описания задачи в [формате изменения поля](#header-формат-измененного-поля)
  + **deadline** - Изменение планируемой даты завершения задачи в [формате изменения поля](#header-формат-измененного-поля)
  + **agentLink** - Изменение контрагента в [формате изменения поля](#header-формат-измененного-поля)
  + **documentLink** - Изменение связанного документа в [формате изменения поля](#header-формат-измененного-поля)
  + **assignee** - Изменение исполнителя в [формате изменения поля](#header-формат-измененного-поля)
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ Parameters
  + id: `bd0dbccf-56ca-11e9-c0a8-100b00000003` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_changed.json) -->

## Задача выполнена [GET]
<h3> Тип уведомления </h3>
NotificationTaskCompleted - задача выполнена
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ Parameters
  + id: `7945a089-56fd-11e9-c0a8-100b00000008` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_completed.json) -->

## Задача удалена [GET]
<h3> Тип уведомления </h3>
NotificationTaskDeleted - задача удалена
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **task** - Задача с заполненным полем name (без id и meta) `Необходимое`
  + **name** - Описание задачи
+ Parameters
  + id: `8d07388c-56cb-11e9-c0a8-100b0000000d` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_deleted.json) -->

## Задача просрочена [GET]
<h3> Тип уведомления </h3>
NotificationTaskOverdue - задача просрочена
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ Parameters
  + id: `51a5b0a3-56e4-11e9-c0a8-100b00000014` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_overdue.json) -->

## Задача переоткрыта [GET]
<h3> Тип уведомления </h3>
NotificationTaskReopened - задача переоткрыта
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ Parameters
  + id: `df0c3e22-56fd-11e9-c0a8-100b0000000a` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_reopened.json) -->

## Новый комментарий к задаче [GET]
<h3> Тип уведомления </h3>
NotificationTaskNewComment - новый комментарий к задаче
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ **noteContent** - Содержимое комментария `Необходимое`
+ Parameters
  + id: `240706df-5704-11e9-c0a8-100b00000003` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_new_comment.json) -->


## Изменен комментарий к задаче [GET]
<h3> Тип уведомления </h3>
NotificationTaskCommentChanged - изменен комментарий к задаче
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ **diff** - Изменения комментария в [формате изменения поля](#header-формат-измененного-поля) `Необходимое`
+ Parameters
  + id: `3d3423ee-5704-11e9-c0a8-100b00000007` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_comment_changed.json) -->

## Удален комментарий к задаче [GET]
<h3> Тип уведомления </h3>
NotificationTaskCommentDeleted - удален комментарий к задаче
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **performedBy** - Сотрудник, выполнивший изменение `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) сотрудника
  + **id** - Идентификатор сотрудника
  + **name** - Имя сотрудника
+ **task** - Задача `Необходимое`
  + **meta** - [Метаданные](#header-метаданные) задачи
  + **id** - Идентификатор Задачи
  + **name** - Описание задачи
  + **deadline** - Планируемая дата завершения задачи
+ **noteContent** - Содержимое удаленного комментария `Необходимое`
+ Parameters
  + id: `3d2abf0f-5704-11e9-c0a8-100b00000005` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/task_comment_deleted.json) -->

## Смена открыта [GET]
<h3> Тип уведомления </h3>
NotificationRetailShiftOpened - смена открыта
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **user** - Ссылка на сотрудника, отрывшего смену `Необходимое`
+ **retailStore** - Ссылка на точку продаж `Необходимое`
+ **retailShift** - Описание смены `Необходимое`
  + **meta** - [Метаданные](#header-метаданные)
  + **id** - Идентификатор смены
  + **name** - Название смены
  + **open** - Дата открытия
  + **proceed** - Сумма внесения
+ Parameters
  + id: `8002409b-351d-11e9-9ff4-34e80002a126` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/retailshift_open.json) -->

## Смена закрыта [GET]
<h3> Тип уведомления </h3>
NotificationRetailShiftClosed - смена закрыта
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Необходимое`
+ **id** - ID Уведомления в формате UUID `Необходимое`
+ **accountId** - ID учетной записи `Необходимое`
+ **created** - Дата и время формирования Уведомления `Необходимое`
+ **read** - Признак того, было ли Уведомление прочитано `Необходимое`
+ **title** - Краткий текст уведомления `Необходимое`
+ **description** - Описание уведомления `Необходимое`
+ **user** - Ссылка на сотрудника, отрывшего смену `Необходимое`
+ **retailStore** - Ссылка на точку продаж `Необходимое`
+ **retailShift** - Описание смены `Необходимое`
  + **meta** - [Метаданные](#header-метаданные)
  + **id** - Идентификатор смены
  + **name** - Название смены
  + **open** - Дата открытия
  + **closed** - Дата закрытия
  + **proceed** - Сумма выручки
+ **sales** - Количество продаж `Необходимое`
+ **returns** - Количество возвратов `Необходимое`
+ Parameters
  + id: `3929d717-351c-11e9-9ff4-34e800029ad4` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/retailshift_closed.json) -->

## Уведомление из сценария [GET]
<h3> Тип уведомления </h3>
NotificationScript - уведомление из сценария
<h3> Атрибуты уведомления </h3>
+ **meta** - [Метаданные](#header-метаданные) объекта `Только для чтения`
+ **id** - ID Уведомления в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **created** - Дата и время формирования Уведомления `Только для чтения`
+ **read** - Признак того, было ли Уведомление прочитано `Только для чтения`
+ **title** - Краткий текст уведомления `Только для чтения`
+ **description** - Описание уведомления `Только для чтения`
+ **eventType** - Тип события сценария `Только для чтения`
  + **ADD** - создан
  + **MODIFY** - изменен
  + **CHANGE_STATUS** - изменен статус
+ **entity** - Ссылка на объект сценария `Только для чтения`
  + **meta** - [Метаданные](#header-метаданные)
      + Допустимые значения **type**:
          + **customerorder** - заказ покупателя
          + **invoiceout** - счет покупателю
          + **demand** - отгрузка
          + **purchaseorder** - заказ поставщику
          + **invoicein** - счет поставщика
          + **supply** - приемка
  + **id** - Идентификатор объекта
  + **name** - Наименование объекта

+ Parameters
  + id: `b22dc861-645b-11eb-0a80-1f8500000044` (required, string) - id Уведомления.
+ Response 200 (application/json)
  + Body
        <!-- include(body/notification/script_notification.json) -->

