# Group Уведомления
## Лента уведомлений [/notification]
### Общие атрибуты уведомлений
+ **meta** - [Метаданные](#header-метаданные) объекта. Содержит тип конкретного уведомления
+ **id** - ID Уведомления в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **created** - Дата и время формирования Уведомления `Только для чтения`
+ **read** - Признак того, было ли Уведомление прочитано
+ **title** - Краткий текст уведомления `Только для чтения`
+ **description** - Описание уведомления `Только для чтения`

### Получить ленту Уведомлений [GET]
Запрос на получение ленты Уведомлений. Результат - объект JSON, включающий в себя поля:
+ **meta** - [Метаданные](#header-метаданные) о выдаче
+ **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос
+ **rows** - Массив JSON объектов, представляющих собой [Уведомления](#уведомления-уведомление)
+ Parameters
  + limit: 1000 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 1000</code>
  </p>
      + Default: `1000`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Уведомлений.
  + Body
        <!-- include(body/notification/get_feed_response.json) -->

## Уведомление [/notification/{id}]
### Получить Уведомление [GET]
Запрос на получение Уведомления с указанным id.
+ Parameters
  + id: `bcd815b9-56ca-11e9-c0a8-100b00000001` (required, string) - id Уведомления.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Уведомления.
  + Body
        <!-- include(body/notification/get_by_id_response.json) -->

### Удалить Уведомление [DELETE]
Запрос на удаление Уведомления. Возможно удаление только Уведомлений текущего пользователя.
+ Parameters
  + id: `bcd815b9-56ca-11e9-c0a8-100b00000001` (required, string) - id Уведомления.
+ Response 200 (application/json)
Успешное удаление Уведомления.
  + Body

## Отметить Уведомление как прочитанное [/notification/{id}/markasread]
### Отметить Уведомление как прочитанное [PUT]
Отметить конкретное уведомление, как прочитанное. Можно отмечать только Уведомления текущего пользователя.
+ Parameters
  + id: `51a5b0a3-56e4-11e9-c0a8-100b00000014` (required, string) - id Уведомления.
+ Response 200 (application/json)
Успешное проставление признака "прочитано".
  + Body

## Отметить все Уведомления как прочитанные [/notification/markasreadall]
### Отметить все Уведомления как прочитанные [PUT]
Отметить все Уведомления текущего пользователя как прочитанные.
+ Response 200 (application/json)
Успешное проставление признака "прочитано" всем непрочитанным Уведомлениям test.
  + Body
