# Group Настройки уведомлений
## Настройки уведомлений [/notification/subscription]
### Атрибуты сущности
+ **groups** - Подписка на уведомления по группам
  + ``groupName`` - Код группы уведомлений.
    + **enabled**: (boolean, required) - Признак "активна" для подписки на уведомления данной группы.
    + **channels**: (array[string], required) - Массив каналов. Содержит значения из списка: `email` (Email-уведомления), `push` (уведомления на мобильных устройствах).

Значения кода группы уведомлений.

| Код группы уведомлений | Описание           |
| ---------------------- |:-------------------|
| `customer_order`       | Заказы покупателей |
| `invoice`              | Счета покупателей  |
| `stock`                | Складские остатки  |
| `retail`               | Розничная торговля |
| `task`                 | Задачи             |
| `data_exchange`        | Обмен данными      |

### Получить настройки уведомлений [GET]
Запрос настроек уведомлений текущего пользователя.
+ Response 200 (application/json)
JSON представление настроек уведомлений.
  + Body
        <!-- include(body/notification/get_subscription_response.json) -->

### Изменить настройки уведомлений [PUT]
Изменение настроек уведомлений текущего пользователя.
+ Request Пример (application/json)
Принимает JSON представление настроек уведомлений.
  + Body
        <!-- include(body/notification/put_subscription_request.json) -->

+ Response 200 (application/json)
Успешное изменение настроек уведомлений текущего пользователя.
  + Body
