# Group Документ Возврат предоплаты
## Возврата предоплаты  [/entity/prepaymentreturn]
Средствами JSON API можно запрашивать списки Возвратов предоплат и сведения по отдельным Возвратам предоплат. Кодом сущности для Возврата предоплаты в составе JSON API является ключевое слово **prepaymentreturn**.

По данной сущности можно осуществлять контекстный поиск с помощью специального параметра `search`. Подробнее можно узнать по [ссылке](#header-контекстный-поиск). Поиск с параметром search отличается от других тем, что поиск не префиксный, без токенизации и идет только по одному полю одновременно. Ищет такие строки, в которые входит значение строки поиска.

Поиск среди объектов предоплат на соответствие поисковой строке будет осуществлён по следующим полям:
+ по наименованию предоплаты **name**

### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) о возврате предоплаты
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **syncId** - ID синхронизации. После заполнения недоступен для изменения.
+ **owner** - Ссылка на Владельца (Сотрудника) в формате [Метаданных](#header-метаданные)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника в формате [Метаданных](#header-метаданные)
+ **version** - Версия сущности `Только для чтения`
+ **updated** - Момент последнего обновления сущности `Только для чтения`
+ **deleted** - Момент последнего удаления сущности `Только для чтения`
+ **name** - номер Возврата предоплаты
+ **description** - Комментарий Возврата предоплаты
+ **externalCode** - Внешний код Возврата предоплаты
+ **moment** - Дата Возврата предоплаты
+ **applicable** - Отметка о проведении
+ **rate** - Валюта
+ **sum** - Сумма Возврата предоплаты в установленной валюте
+ **agent** - Ссылка на контрагента в формате [Метаданных](#header-метаданные) `Необходимое`
+ **organization** - Ссылка на ваше юрлицо в формате [Метаданных](#header-метаданные)
+ **state** - Статус Возврата предоплаты в формате [Метаданных](#header-метаданные)
+ **attributes** - Коллекция доп. полей в формате [Метаданных](#header-метаданные)
+ **documents** - Список печатных форм в формате [Метаданных](#header-метаданные)
<br>Поля при expand'е:</br>
  - **name** - номер документа
  - **moment** - дата печати
  - **href** - ссылка на файл печатной формы
  - **fileName** - название файла печатной формы
  - **updated** - дата последнего изменения
+ **created** - Дата создания `Только для чтения`
+ **vatEnabled** - Учитывается ли НДС
+ **vatIncluded** - Включен ли НДС в цену
+ **vatSum** - Сумма НДС `Только для чтения`
+ **retailStore** - Ссылка на точку продаж в формате [Метаданных](#header-метаданные)
+ **retailShift** - Ссылка на Розничную смену, в рамках которой был проведен возврат предоплаты в формате [Метаданных](#header-метаданные) `Необходимое`
+ **prepayment** - Ссылка на Предоплату в формате [Метаданных](#header-метаданные) `Необходимое`
+ **cashSum**  - Возврат наличными
+ **noCashSum** - Возврат картой
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

<!-- include(rate.apib) -->

### Позиции Возврата предоплаты
Позиции Возврата предоплаты - это список товаров/услуг/модификаций/серий.
Объект позиции Возврата предоплаты содержит следующие поля:
+ **id** - ID товара в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **quantity** - Количество товаров/услуг данного вида в позиции. Если позиция - товар, у которого включен учёт по серийным номерам, то значение в этом поле всегда будет равно количеству серийных номеров для данной позиции в документе.
+ **price** - Цена товара/услуги в копейках
+ **discount** - Процент скидки или наценки. Наценка указывается отрицательным числом, т.е. -10 создаст наценку в 10%
+ **vat** - НДС, которым облагается текущая позиция
+ **assortment** - Ссылка на товар/услугу/серию/модификацию, которую представляет собой позиция, в формате [Метаданных](#header-метаданные)
+ **pack** - Упаковка товара

### Атрибуты доступные для фильтрации
+ **id** - ID в формате UUID
+ **syncId** - ID синхронизации
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **updatedBy** - Автор последнего обновления сущности в формате `uid` (`admin@admin`)
+ **deleted** - Момент последнего удаления сущности
+ **name** - номер Возврата предоплаты
+ **description** - Комментарий Возврата предоплаты
+ **externalCode** - Внешний код Возврата предоплаты
+ **moment** - Дата Возврата предоплаты
+ **applicable** - Отметка о проведении
+ **sum** - Сумма Возврата предоплаты в установленной валюте
+ **owner** - Ссылка на Владельца (Сотрудника)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника
+ **organization** - Ссылка на ваше юрлицо
+ **agent** - Ссылка на контрагента
+ **state** - Статус Возврата предоплаты
+ **created** - Дата создания
+ **isDeleted** - Удален ли Возврат предоплаты

### Атрибуты доступные для сортировки
+ **id** - ID в формате UUID
+ **syncId** - ID синхронизации
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **name** - номер Возврата предоплаты
+ **description** - Комментарий Возврата предоплаты
+ **externalCode** - Внешний код Возврата предоплаты
+ **moment** - Дата Возврата предоплаты
+ **applicable** - Отметка о проведении
+ **sum** - Сумма Возврата предоплаты в установленной валюте
+ **created** - Дата создания

### Получить Возвраты предоплаты [GET]
Запрос всех Возвратов предоплат на данной учётной записи.
Результат: Объект JSON, включающий в себя поля:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой Возвраты предоплаты.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Возвратов предоплат.
  + Body
        <!-- include(body/prepaymentreturn/get_list.json) -->

## Метаданные Возвратов предоплат [/entity/prepaymentreturn/metadata]
### Метаданные Возвратов предоплат [GET]
Запрос на получение метаданных Возвратов предоплат. Результат - объект JSON, включающий в себя:
+ **meta** - Ссылка на метаданные Возвратов предоплат
+ **attributes** - Массив объектов доп. полей Возвратов предоплат в формате [Метаданных](#header-метаданные)
+ **states** - Массив статусов Возвратов предоплат
+ **createShared** - создавать новые Возвраты предоплат с меткой "Общий"

Структура отдельного объекта, представляющего доп. поле подробно описана в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями).

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление доп. полей Возвратов предоплат.
  + Body
        <!-- include(body/prepaymentreturn/metadata.json) -->

## Отдельное доп. поле [/entity/prepaymentreturn/metadata/attributes/{id}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Доп. поля
### Отдельное доп. поле [GET]
Запрос на получение информации по отдельному дополнительному полю.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельного доп. поля.
  + Body
        <!-- include(body/prepaymentreturn/metadata_by_id.json) -->

## Возврат предоплаты [/entity/prepaymentreturn/{id}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Возврата предоплаты
### Получить Возврат предоплаты [GET]
Запрос на получение отдельного Возврата предоплаты с указанным id.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Возврата предоплаты.
  + Body
        <!-- include(body/prepaymentreturn/get_by_id.json) -->

### Удалить Возврат предоплаты [DELETE /entity/prepaymentreturn/{id}]
Запрос на удаление Возврата предоплаты с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Возврата предоплаты

+ Response 200 (application/json)
Успешное удаление Возврата предоплаты.
  + Body

## Позиции Возврата предоплаты [/entity/prepaymentreturn/{id}/positions]
Отдельный ресурс для управления позициями Возврата предоплаты. С его помощью вы можете запросить позиции большого документа, количество строк в котором превышает лимит на количество строк в выдаче документа. Этот лимит равен 100. Более подробно о лимитах на количество строк документа и работе с большими документами можно прочитать [тут](#header-работа-с-позициями-документов).
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Предоплаты

### Получить позиции Возврата предоплаты [GET]
Запрос на получение списка всех позиций данного Возврата предоплаты.
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой позиции Возврата предоплаты.

+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка позиций отдельного Предоплаты.
  + Body
        <!-- include(body/prepaymentreturn/positions_get_list.json) -->

## Позиция Возврата предоплаты [/entity/prepaymentreturn/{id}/positions/{positionID}]
Отдельная позиция Возврата предоплаты с указанным id позиции.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Предоплаты
  + positionID: `34f6344f-015e-11e6-9464-e4de0000006c` (required, string) - id позиции Предоплаты

### Получить позицию Возврата предоплаты [GET]
Запрос на получение отдельной позиции Возврата предоплаты с указанным id.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельной позиции Возврата предоплаты.
  + Body
        <!-- include(body/prepaymentreturn/position_get_by_id.json) -->
