# Group Группа товаров
## Группы товаров [/entity/productfolder]
Средствами JSON API можно создавать и обновлять сведения о Группах товаров, запрашивать списки Групп товаров и сведения по отдельным Группам товаров. Кодом сущности для Группы товаров в составе JSON API является ключевое слово **productFolder**.
По данной сущности можно осуществлять контекстный поиск с помощью специального параметра `search`. Подробнее можно узнать по [ссылке](#header-контекстный-поиск).

Поиск среди объектов групп товаров на соответствие поисковой строке будет осуществлён по следующим полям:
+ по наименованию Группы товаров (name)
+ по коду Группы товаров (code)

### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) о Группе товаров
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **owner** - Ссылка на Владельца (Сотрудника) в формате [Метаданных](#header-метаданные))
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника в формате [Метаданных](#header-метаданные)
+ **version** - Версия сущности `Только для чтения`
+ **updated** - Момент последнего обновления сущности `Только для чтения`
+ **name** - Наименование Группы товаров `Необходимое`
+ **description** - Описание Группы товаров
+ **code** - Код Группы товаров
+ **externalCode** - Внешний код Группы товаров
+ **archived** - Добавлена ли Группа товаров в архив `Только для чтения`
+ **pathName** - Наименование Группы товаров, в которую входит данная Группа товаров `Только для чтения`
+ **vat** - НДС %
+ **effectiveVat** - Реальный НДС % `Только для чтения`
+ **productFolder** - Ссылка на Группу товаров данной Группы товаров в формате [Метаданных](#header-метаданные)

### Атрибуты доступные для фильтрации
+ **id** - ID в формате UUID
+ **owner** - Ссылка на Владельца (Сотрудника)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **updatedBy** - Автор последнего обновления сущности в формате `uid` (`admin@admin`)
+ **name** - Наименование Группы товаров
+ **description** - Описание Группы товаров
+ **code** - Код Группы товаров
+ **externalCode** - Внешний код Группы товаров
+ **archived** - Добавлена ли Группа товаров в архив
+ **pathName** - Наименование Группы товаров, в которую входит данная Группа товаров

### Атрибуты доступные для сортировки
+ **id** - ID в формате UUID
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **name** - Наименование Группы товаров
+ **externalCode** - Внешний код Группы товаров
+ **archived** - Добавлена ли Группа товаров в архив
+ **pathName** - Наименование Группы товаров, в которую входит данная Группа товаров

### Получить список групп товаров [GET]
Запрос всех Групп товаров на данной учётной записи.
Результат: Объект JSON, включающий в себя поля:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой Группы товаров.

+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Групп товаров.
  + Body
        <!-- include(body/productFolder/get_list.json) -->

### Создать новую группу товаров [POST]
Запрос на создание новой Группы товаров.
Обязательные для создания Группы товаров поля:
+ **name** - Наименование Группы товаров

+ Request Пример 1 (application/json)
Пример создания новой Группы товаров с телом запроса, содержащим только поле name.
  + Body
        <!-- include(body/productFolder/post_short_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданной Группы товаров.
  + Body
        <!-- include(body/productFolder/post_short_response.json) -->

+ Request Пример 2 (application/json)
Пример создания новой Группы товаров с более насыщенным телом запроса.
  + Body
        <!-- include(body/productFolder/post_long_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданной Группы товаров.
  + Body
        <!-- include(body/productFolder/post_long_response.json) -->

### Удалить Группу товаров [DELETE /entity/productfolder/{id}]
Запрос на удаление Группы товаров с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Группы товаров

+ Response 200 (application/json)
Успешное удаление Группы товаров.
  + Body

## Метаданные Групп товаров [/entity/productfolder/metadata]
### Метаданные Групп товаров [GET]
Запрос на получение метаданных Групп товаров. Результат - объект JSON, включающий в себя:
+ **meta** - Ссылка на метаданные Групп товаров
+ **attributes** - Массив объектов доп. полей Групп товаров в формате [Метаданных](#header-метаданные)
+ **createShared** - создавать новые Группы товаров с меткой "Общий"

Структура отдельного объекта, представляющего доп. поле подробно описана в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями).

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление доп. полей Групп товаров.
  + Body
        <!-- include(body/productFolder/get_metadata.json) -->

## Отдельное доп. поле [/entity/productfolder/metadata/attributes/{id}]
+ Parameters
  + id: `5290a290-0313-11e6-9464-e4de00000020` (required, string) - id Доп. поля
### Отдельное доп. поле [GET]
Запрос на получение информации по отдельному дополнительному полю.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельного доп. поля.
  + Body
        <!-- include(body/productFolder/metadata_by_id.json) -->

## Группа товаров [/entity/productfolder/{id}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Группы товаров

### Получить Группу товаров [GET]
Запрос на получение отдельной группы товаров с указанным id.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Группы товаров.
  + Body
        <!-- include(body/productFolder/get_by_id.json) -->

### Изменить Группу товаров [PUT]
Запрос на обновление Группы товаров с указанным id.
В теле запроса можно указать только те поля, которые необходимо изменить у Группы товаров, кроме тех, что
помечены `Только для чтения` в описании [атрибутов Группы товаров](#группа-товаров-группы-товаров).
Для обновления поля **pathName** нужно обновить ссылку на родительскую Группу товаров, т.е. обновить поле
**productFolder**

+ Request Пример (application/json)
Пример запроса на обновление конкретной Группы товаров.
  + Body
        <!-- include(body/productFolder/put_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление обновлённой Группы товаров.
  + Body
        <!-- include(body/productFolder/put_response.json) -->


# Data Structures

## ProductFolder (Legendable Entity)
+ vat: 10 (string, optional) - НДС %
+ effectiveVat: 10 (string, optional)- Реальный НДС %
+ pathName: Группа1 (string, optional) - Наименование группы товаров, в которую входит данная Группа товаров
+ productFolder: (MetaRef, optional) - Ссылка на родительскую группу товаров

## ProductFolder List (object)
+ context: (Context, required)
+ meta: (Meta, required)
+ rows: (array[ProductFolder], required, fixed) - Массив Групп товаров
