# Group Регион
## Регионы [/entity/region]
Средствами JSON API можно запрашивать список регионов России и сведения по отдельным регионам. Кодом сущности для Регионов в составе JSON API является ключевое слово **region**.
По данной сущности можно осуществлять контекстный поиск с помощью специального параметра `search`. Подробнее можно узнать по [ссылке](#header-контекстный-поиск). Поиск с параметром search отличается от других тем, что поиск не префиксный, без токенизации и идет только по одному полю одновременно. Ищет такие строки, в которые входит значение строки поиска.

Поиск среди регионов на соответствие поисковой строке будет осуществлён по следующим полям:
+ по наименованию Региона **name**

### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) о Регионе
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **version** - Версия сущности `Только для чтения`
+ **updated** - Момент последнего обновления сущности `Только для чтения`
+ **name** - Наименование Региона `Необходимое`
+ **code** - Код Региона
+ **externalCode** - Внешний код Региона

### Атрибуты доступные для фильтрации
+ **id** - ID в формате UUID
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **name** - Наименование Региона
+ **code** - Код Региона
+ **externalCode** - Внешний код Региона

### Атрибуты доступные для сортировки
+ **id** - ID в формате UUID
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **name** - Наименование Региона
+ **code** - Код Региона
+ **externalCode** - Внешний код Региона

### Получить Регионы [GET]
Запрос на получение списка Регионов.
Результат: Объект JSON, включающий в себя поля:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой Региона.

+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Регионов.
  + Body
        <!-- include(body/region/get_list.json) -->

## Регион [/entity/region/{id}]
+ Parameters
  + id: `00000000-0000-0000-0000-000000000077` (required, string) - id Региона

## Получить Регион [GET]
Запрос на получение региона с указанным id.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Региона с указанным id.
  + Body
        <!-- include(body/region/get_by_id.json) -->
