# group Документ Выплата денег
Средствами JSON API можно создавать и обновлять сведения о выплатах денег, запрашивать списки выплат денег и сведения по отдельным выплатам денег. Кодом сущности для внесения денег в составе JSON API является ключевое слово **retaildrawercashout**. Больше о выплатах денег и работе с ними в основном интерфейсе вы можете прочитать в нашей службе поддержки по  [этой ссылке](https://support.moysklad.ru/hc/ru/articles/203325423-%D0%A0%D0%BE%D0%B7%D0%BD%D0%B8%D1%86%D0%B0#11)
## Выплаты денег [/entity/retaildrawercashout/]
### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) о выплате денег
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **syncId** - ID синхронизации. После заполнения недоступен для изменения.
+ **version** - Версия сущности `Только для чтения`
+ **updated** - Момент последнего обновления сущности `Только для чтения`
+ **deleted** - Момент последнего удаления сущности `Только для чтения`
+ **name** - номер выплаты денег
+ **description** - Комментарий выплаты денег
+ **externalCode** - Внешний код выплаты денег
+ **moment** - Дата выплаты
+ **applicable** - Отметка о проведении
+ **sum** - Сумма выплата в установленной валюте `Только для чтения`
+ **rate** - Валюта
+ **owner** - Ссылка на Владельца (Сотрудника) в формате [Метаданных](#header-метаданные)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника в формате [Метаданных](#header-метаданные)
+ **organization** - Ссылка на ваше юрлицо в формате [Метаданных](#header-метаданные) `Необходимое`
+ **agent** - Ссылка на сотрудника, которому была совершена выплата, в формате [Метаданных](#header-метаданные) `Необходимое`
+ **state** - Статус выплаты в формате [Метаданных](#header-метаданные)
+ **attributes** - Коллекция доп. полей в формате [Метаданных](#header-метаданные)
+ **documents** - Список печатных форм в формате [Метаданных](#header-метаданные)
<br>Поля при expand'е:</br>
  - **name** - номер документа
  - **moment** - дата печати
  - **href** - ссылка на файл печатной формы
  - **fileName** - название файла печатной формы
  - **updated** - дата последнего изменения
+ **created** - Дата создания `Только для чтения`
<h3>Связи с другими документами</h3>
+ **retailShift** - Ссылка на розничную смену, в рамках которой была выполнена выплата денег в формате [Метаданных](#header-метаданные) `Необходимое`

<!-- include(rate.apib) -->

### Атрибуты доступные для фильтрации
+ **id** - ID в формате UUID
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **updatedBy** - Автор последнего обновления сущности в формате `uid` (`admin@admin`)
+ **deleted** - Момент последнего удаления сущности
+ **name** - номер выплаты денег
+ **description** - Комментарий выплаты денег
+ **externalCode** - Внешний код выплаты денег
+ **moment** - Дата выплаты
+ **applicable** - Отметка о проведении
+ **sum** - Сумма выплата в установленной валюте
+ **owner** - Ссылка на Владельца (Сотрудника)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника
+ **organization** - Ссылка на ваше юрлицо
+ **agent** - Ссылка на сотрудника, которому была совершена выплата,
+ **state** - Статус выплаты
+ **created** - Дата создания
+ **isDeleted** - Удалена ли выплата денег
+ **retailShift** - Ссылка на смену

### Атрибуты доступные для сортировки
+ **id** - ID в формате UUID
+ **syncId** - ID синхронизации
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **name** - номер выплаты денег
+ **externalCode** - Внешний код выплаты денег
+ **moment** - Дата выплаты
+ **applicable** - Отметка о проведении
+ **sum** - Сумма выплата в установленной валюте
+ **created** - Дата создания

### Получить выплаты денег [GET]
Запрос на получение всех выплат денег на данной учётной записи.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

  + search: `0001` (optional, string)
    URL Параметр для поиска по имени документа.
    Фильтр документов по указанной поисковой строке. Фильтрация происходит по
    полю name.

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка выплат денег.
  + Body
        <!-- include(body/retaildrawercashout/get_list.json) -->

### Создать выплату денег [POST]
Запрос на создание выплаты денег.

+ Request Пример 1 (application/json)
Пример создания новой выплаты денег.
  + Body
        <!-- include(body/retaildrawercashout/post_request.json) -->
+ Response 200
  + Body
        <!-- include(body/retaildrawercashout/post_response.json) -->

### Удалить Выплату денег [DELETE /entity/retaildrawercashout/{id}]
Запрос на удаление Выплаты денег с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id выплаты денег

+ Response 200 (application/json)
Успешное удаление Выплаты денег.
  + Body

## Метаданные выплат денег [/entity/retaildrawercashout/metadata]
### Метаданные выплат денег [GET]
Запрос на получение метаданных выплат денег. Результат - объект JSON, включающий в себя:
+ **meta** - Ссылка на метаданные выплат денег
+ **attributes** - Массив объектов доп. полей выплат денег в формате [Метаданных](#header-метаданные)
+ **states** - Массив статусов выплат денег
+ **createShared** - создавать новые выплаты денег с меткой "Общий"

Структура отдельного объекта, представляющего доп. поле подробно описана в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями).

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление доп. полей выплат денег.
  + Body
        <!-- include(body/retaildrawercashout/get_metadata.json) -->

## Отдельное доп. поле [/entity/retaildrawercashout/metadata/attributes/{id}]
+ Parameters
  + id: `5290a290-0313-11e6-9464-e4de00000020` (required, string) - id Доп. поля
### Отдельное доп. поле [GET]
Запрос на получение информации по отдельному дополнительному полю.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельного доп. поля.
  + Body
        <!-- include(body/retaildrawercashout/metadata_by_id.json) -->

## Шаблон выплаты денег [/entity/retaildrawercashout/new]
### Шаблон выплаты денег [PUT]
Запрос на получение предзаполненого стандартными значениями шаблона выплаты денег без связи с каким-либо документом.

+ Request Пустое тело запроса (application/json)

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление предзаполненной выплаты денег.
  + Body
        <!-- include(body/retaildrawercashout/new_empty.json) -->

### Шаблон выплаты денег на основе [PUT]
Запрос на получение предзаполненной выплаты денег на основе розничной смены.
В результате запроса, будет создан предзаполненный шаблон выплаты денег на основе переданной
розничной смены.

+ Request Пример с розничной сменой (application/json)
Запрос на создание выплаты денег на основе розничной смены.
  + Body
        <!-- include(body/retaildrawercashout/new_shift_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление предзаполненной выплаты денег.
  + Body
        <!-- include(body/retaildrawercashout/new_shift_response.json) -->

## Выплата денег [/entity/retaildrawercashout/{id}]

### Получить выплату денег [GET]
Запрос на получение отдельной выплаты денег с указанным id.

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление выплаты денег с указанным id.
  + Body
        <!-- include(body/retaildrawercashout/get_by_id.json) -->

### Изменить выплачу денег [PUT]
Запрос на обновление выплаты денег.
+ Request Пример 1 (application/json)
Пример обновления выплаты денег.
  + Body
        <!-- include(body/retaildrawercashout/put_request.json) -->
+ Response 200
  + Body
        <!-- include(body/retaildrawercashout/put_response.json) -->
