# Group Документ Возврат покупателя
Средствами JSON API можно создавать и обновлять сведения о Возвратах покупателей, запрашивать списки Возвратов покупателей и сведения по отдельным Возвратам покупателей. Позициями Возвратов покупателей можно управлять как в составе отдельного Возврата, так и отдельно - с помощью специальных ресурсов для управления позициями Возврата покупателя. Кодом сущности для Возврата покупателя в составе JSON API является ключевое слово **salesreturn**.
## Возвраты покупателей [/entity/salesreturn]
### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) о Возврате покупателя
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **syncId** - ID синхронизации. После заполнения недоступен для изменения.
+ **version** - Версия сущности `Только для чтения`
+ **updated** - Момент последнего обновления сущности `Только для чтения`
+ **deleted** - Момент последнего удаления сущности `Только для чтения`
+ **name** - номер Возврата покупателей
+ **description** - Комментарий Возврата покупателей
+ **externalCode** - Внешний код Возврата покупателей
+ **moment** - Дата Возврата покупателей
+ **applicable** - Отметка о проведении
+ **vatEnabled** - Учитывается ли НДС
+ **vatIncluded** - Включен ли НДС в цену
+ **sum** - Сумма Возврата покупателей в копейках `Только для чтения`
+ **rate** - Валюта
+ **owner** - Ссылка на Владельца (Сотрудника) в формате [Метаданных](#header-метаданные)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника в формате [Метаданных](#header-метаданные)
+ **organization** - Ссылка на ваше юрлицо в формате [Метаданных](#header-метаданные) `Необходимое`
+ **agent** - Ссылка на контрагента в формате [Метаданных](#header-метаданные)
+ **store** - Ссылка на склад в формате [Метаданных](#header-метаданные) `Необходимое`
+ **contract** - Ссылка на договор в формате [Метаданных](#header-метаданные)
+ **project** - Ссылка на проект в формате [Метаданных](#header-метаданные)
+ **state** - Статус Возврата покупателей в формате [Метаданных](#header-метаданные)
+ **organizationAccount** - Ссылка на счёт вашего юрлица в формате [Метаданных](#header-метаданные)
+ **agentAccount** - Ссылка на счёт контрагента в формате [Метаданных](#header-метаданные)
+ **attributes** - Коллекция доп. полей в формате [Метаданных](#header-метаданные)
+ **documents** - Список печатных форм в формате [Метаданных](#header-метаданные)
<br>Поля при expand'е:</br>
  - **name** - номер документа
  - **moment** - дата печати
  - **href** - ссылка на файл печатной формы
  - **fileName** - название файла печатной формы
  - **updated** - дата последнего изменения
+ **created** - Дата создания `Только для чтения`
+ **vatSum** - Сумма НДС `Только для чтения`
+ **positions** - Ссылка на позиции Возврата покупателей в формате [Метаданных](#header-метаданные)
<h3>Связи с другими документами</h3>
+ **demand** - Ссылка на отгрузку, по которой произошёл возврат в формате [Метаданных](#header-метаданные) Поле является необходимым для возврата с основанием.
+ **losses** - Массив ссылок на связанные списания в формате [Метаданных](#header-метаданные)
+ **payments** - Массив ссылок на связанные платежи в формате [Метаданных](#header-метаданные)
+ **payedSum** - Сумма исходящих платежей по возврату покупателя
+ **factureOut** - Ссылка на Счет-фактуру выданный, с которым связан этот возврат, в формате [Метаданных](#header-метаданные)

### Позиции Возврата покупателя
Позиции Возврата покупателей - это список товаров/услуг/модификаций/серий.
Объект позиции Возврата покупателей содержит следующие поля:
+ **id** - ID позиции в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **quantity** - Количество товаров/услуг данного вида в позиции. Если позиция - товар, у которого включен учёт по серийным номерам, то значение в этом поле всегда будет равно количеству серийных номеров для данной позиции в документе.
+ **price** - Цена товара/услуги в копейках. Должна совпадать с указанной в продаже
+ **discount** - Процент скидки или наценки. Должен совпадать с указанным в отгрузке (игнорируется для возвратов без основания)
+ **vat** - НДС, которым облагается текущая позиция. Должен совпадать с указанным в продаже
+ **assortment** - Ссылка на товар/услугу/серию/модификацию, которую представляет собой позиция, в формате [Метаданных](#header-метаданные)
+ **pack** - Упаковка товара
+ **cost** - Себестоимость за единицу в копейках. Можно задать только для возвратов без основания.
+ **things** - Серийные номера
Значение данного атрибута игнорируется, если товар позиции не находится на серийном учете.
В ином случае количество товаров в позиции будет равно количеству серийных номеров, переданных в значении атрибута.

С позициями можно работать с помощью специальных [ресурсов для управления позициями Возврата покупателей](#документ-возврат-покупателя-позиции-возврата-покупателя),
а также в составе отдельного Возврата покупателей. При работе в составе отдельного Возврата покупателей,
вы можете отправлять запросы на создание отдельного Возврата покупателей с включенным в тело запроса
массивом позиций Возврата покупателей. Если количество позиций превышает максимально допустимое, то для
дальнейшего пополнения позиций нужно будет работать со специальным ресурсом "Позиции Возврата покупателей".
Также, при работе в составе отдельного Возврата покупателей, можно отправлять запросы на обновление списка позиций
с включенным в тело запроса массивом позиций Возврата покупателей. При этом важно помнить, что коллекция позиций будет
восприниматься как "все позиции Возврата покупателей" и полностью заменит уже существующую коллекцию при обновлении объекта - лишние
позиции будут удалены, новые добавлены, существующие - изменены.
+ **gtd** - ГТД
+ **country** - Ссылка на страну в формате [Метаданных](#header-метаданные)


<!-- include(rate.apib) -->

О работе с доп. полями Возвратов покупателейых возвратов можно прочитать [здесь](#header-работа-с-дополнительными-полями)

### Атрибуты доступные для фильтрации
+ **id** - ID в формате UUID
+ **syncId** - ID синхронизации
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **updatedBy** - Автор последнего обновления сущности в формате `uid` (`admin@admin`)
+ **deleted** - Момент последнего удаления сущности
+ **name** - номер Возврата покупателей
+ **description** - Комментарий Возврата покупателей
+ **externalCode** - Внешний код Возврата покупателей
+ **moment** - Дата Возврата покупателей
+ **applicable** - Отметка о проведении
+ **sum** - Сумма Возврата покупателей в копейках
+ **owner** - Ссылка на Владельца (Сотрудника)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника
+ **organization** - Ссылка на ваше юрлицо
+ **agent** - Ссылка на контрагента
+ **store** - Ссылка на склад
+ **contract** - Ссылка на договор
+ **project** - Ссылка на проект
+ **state** - Статус Возврата покупателей
+ **created** - Дата создания
+ **isDeleted** - Удален ли возврат покупателя

### Атрибуты доступные для сортировки
+ **id** - ID в формате UUID
+ **syncId** - ID синхронизации
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **name** - номер Возврата покупателей
+ **description** - Комментарий Возврата покупателей
+ **externalCode** - Внешний код Возврата покупателей
+ **moment** - Дата Возврата покупателей
+ **applicable** - Отметка о проведении
+ **sum** - Сумма Возврата покупателей в копейках
+ **created** - Дата создания

### Получить Возвраты покупателей [GET]
Запрос всех Возвратов покупателей на данной учётной записи.
Результат: Объект JSON, включающий в себя поля:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой Возвраты покупателей.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Возвратов покупателей.
  + Body
        <!-- include(body/sales_return/get_list.json) -->

### Создать Возврат покупателя [POST]
Обязательные поля при создании нового Возврата покупателей:
+ **name** - Номер возврата, если не будет указан, будет сгенерирован автоматически
+ **organization** - Ссылка на ваше юрлицо в формате [Метаданных](#header-метаданные)
+ **store** - Ссылка на склад в формате [Метаданных](#header-метаданные)
+ **demand** - Ссылка на отгрузку, по которой произошёл возврат в формате [Метаданных](#header-метаданные), обязательное поле только для возврата по основанию
+ **agent** - Ссылка на контрагента в формате [Метаданных](#header-метаданные)
Контрагент, указанный в запросе на создание возврата, должен совпадать с контрагентом, указанном в документе,
по которому создаётся возврат.

При создании возврата:
+ При создании возврата без основания поле **demand** указывать не нужно
+ Контрагент в возврате и в документе, по которому он создаётся, должны совпадать
+ Валюта и юрлицо в возврате и в документе так же должны совпадать
+ При создании возврата на основании другого документа позиции, передаваемые в коллекции **positions**, 
должны соответствовать позициям документа-основания. Можно задать количество товара в позиции, но не больше, 
чем в документе-основании. Нельзя передавать позиции, которых нет в документе-основании и менять значение поля **price**.

+ Request На основании (application/json)
Пример создания нового Возврата покупателя на основании отгрузки.
  + Body
        <!-- include(body/sales_return/post_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Возврата покупателя.
  + Body
        <!-- include(body/sales_return/post_response.json) -->

+ Request Без основания (application/json)
Пример создания нового Возврата покупателя без основания.
  + Body
        <!-- include(body/sales_return/post_request_without_demand.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Возврата покупателя.
  + Body
        <!-- include(body/sales_return/post_response_without_demand.json) -->

### Удалить Возврат покупателя [DELETE /entity/salesreturn/{id}]
Запрос на удаление Возврата покупателей с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Возврата покупателей

+ Response 200 (application/json)
Успешное удаление Возврата покупателей.
  + Body

## Метаданные Возвратов покупателей [/entity/salesreturn/metadata]
### Метаданные Возвратов покупателей [GET]
Запрос на получение метаданных Возвратов покупателей. Результат - объект JSON, включающий в себя:
+ **meta** - Ссылка на метаданные Возвратов покупателей
+ **attributes** - Массив объектов доп. полей Возвратов покупателей в формате [Метаданных](#header-метаданные)
+ **states** - Массив статусов Возвратов покупателей
+ **createShared** - создавать новые Возвраты покупателей с меткой "Общий"

Структура отдельного объекта, представляющего доп. поле подробно описана в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями).

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление доп. полей Возвратов покупателей.
  + Body
        <!-- include(body/sales_return/get_metadata.json) -->

## Отдельное доп. поле [/entity/salesreturn/metadata/attributes/{id}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Доп. поля
### Отдельное доп. поле [GET]
Запрос на получение информации по отдельному дополнительному полю.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельного доп. поля.
  + Body
        <!-- include(body/sales_return/metadata_by_id.json) -->

## Шаблон возврата покупателя [/entity/salesreturn/new]
### Шаблон возврата покупателя [PUT]
Запрос на получение предзаполненого стандартными значениями шаблона возврата покупателя без связи с каким-либо документом.

+ Request Пустое тело запроса (application/json)
Создание шаблона возврата покупателя с пустым телом запроса

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление предзаполненного возврата покупателя.
  + Body
        <!-- include(body/sales_return/new_empty_response.json) -->

### Шаблон возврата покупателя на основе [PUT]
Запрос на получение предзаполненного шаблона возврата покупателя на основе переданной отгрузки.
В ответ на запрос вернётся предзаполненный шаблон возврата покупателя, который
затем можно будет использовать для создания нового возврата с помощью POST запроса.

+ Request Создание на основе отгрузки (application/json)
Пример запроса на создание шаблона возврата покупателя на основе отгрузки.
  + Body
        <!-- include(body/sales_return/new_base_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление предзаполненного Возврата покупателя.
  + Body
        <!-- include(body/sales_return/new_base_response.json) -->


## Возврат покупателя [/entity/salesreturn/{id}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Возврата покупателя
### Получить Возврат покупателя [GET]
Запрос на получение отдельного Возврата покупателей с указанным id.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Возврата покупателей с указанным id.
  + Body
        <!-- include(body/sales_return/get_by_id.json) -->

### Изменить Возврат покупателя [PUT]
Запрос на обновление Возврата покупателей с указанным id.
В теле запроса можно указать только те поля, которые необходимо изменить у Возврата покупателей, кроме тех, что
помечены `Только для чтения` в описании [атрибутов Возврата покупателей](#документ-возврат-покупателя-возвраты-покупателей).
При обновлении поля **organization** нужно также обновить поле **organizationAccount** иначе произойдёт ошибка.
Контрагент должен совпадать с контрагентом, указанным в документе, по которому создаётся возврат.

При обновлении возврата:
+ Нельзя изменять следующие поля: **agentAccount**, **agent**, **demand**
+ Нельзя выставить валюту отличную от валюты в документе
+ Нельзя добавить позиции, отсутствующие среди позиций документа.

+ Request Пример (application/json)
Пример запроса на обновление Возврата покупателей.
  + Body
        <!-- include(body/sales_return/put_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление обновлённого Возврата покупателей.
  + Body
        <!-- include(body/sales_return/put_response.json) -->


## Позиции возврата покупателя [/entity/salesreturn/{id}/positions]
Отдельный ресурс для управления позициями Возврата покупателей. С его помощью вы можете управлять позициями большого документа, количество строк в котором превышает лимит на количество строк, сохраняемых вместе с документом. Этот лимит равен 100. Более подробно о лимитах на количество строк документа и работе с большими документами можно прочитать [тут](#header-работа-с-позициями-документов).
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Возврата покупателей
### Получить Позиции [GET]
Запрос на получение списка всех позиций данной Возврата покупателей.
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой позиции Возврата покупателей.
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка позиций Возврата покупателей.
  + Body
        <!-- include(body/sales_return/positions_get_list.json) -->


### Создать Позицию [POST]
Запрос на создание новой позиции в Возврате покупателя.
Для успешного создания необходимо в теле запроса указать следующие поля:
+ **assortmet** - Ссылка на товар/услугу/серию/модификацию, которую представляет собой позиция.
Также можно указать поле с именем **service**, **consignment**, **variant** в соответствии с тем,
чем является указанная позиция. Подробнее об этом поле можно прочитать в описании [позиции Возврата покупателей](#header-позиции-возврата-покупателя).
+ **quantity** - Количество указанной позиции. Должно быть положительным, иначе возникнет ошибка.
Одновременно можно создать как одну так и несколько позиций Возврата покупателей. Все созданные данным запросом позиции
будут добавлены к уже существующим.
Нельзя создавать позиции, отличные от позиций в документе, по которому создаётся возврат. Допустимо только
отличие в **quantity** позиций (количество в позиции в возврате м.б. меньше или равно количеству в позиции в документе).

+ Request Пример (application/json)
Пример запроса на создание позиций в Возврате покупателя.
  + Body
        <!-- include(body/sales_return/positions_post_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданных позиций.
  + Body
        <!-- include(body/sales_return/positions_post_response.json) -->

## Позиция Возврата покупателя [/entity/salesreturn/{id}/positions/{positionID}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Возврата покупателей
  + positionID: `34f6344f-015e-11e6-9464-e4de0000006c` (required, string) - id позиции Возврата покупателей
### Получить Позицию [GET]
Запрос на получение отдельной позиции Возврата покупателей с указанным id.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельной позиции Возврата покупателей.
  + Body
        <!-- include(body/sales_return/positions_get_by_id.json) -->
### Изменить Позицию [PUT]
Запрос на обновление отдельной позиции Возврата покупателей.
При обновлении отдельной позиции в возврате можно только изменить количество данной позиции.
Причём это количество должно быть в пределах [1, n], где n - кол-во данной позиции в документе, по которому создан возврат.
+ Request Пример (application/json)
Пример запроса на обновление отдельной позиции в Возврате покупателя.
  + Body
        <!-- include(body/sales_return/positions_put_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление обновлённой позиции Возврата покупателей.
  + Body
        <!-- include(body/sales_return/positions_put_response.json) -->

### Удалить позицию [DELETE]
Запрос на удаление отдельной позиции Возврата покупателей с указанным id.

+ Response 200 (application/json)
Успешное удаление позиции Возврата покупателей.
  + Body
