# Group Услуга
Средствами JSON API можно создавать и обновлять сведения об Услугах, запрашивать списки Услуг и сведения по отдельным Услугам. Кодом сущности для Услуги в составе JSON API является ключевое слово **service**. Услуга - специальная разновидность товара, без закупочной цены и упаковок. Больше о Товарах и работе с ними в основном интерфейсе вы можете прочитать в нашей службе поддержки в разделе
 [Товары и склад](https://support.moysklad.ru/hc/ru/sections/200564973-%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D1%8B-%D0%B8-%D1%81%D0%BA%D0%BB%D0%B0%D0%B4).
По данной сущности можно осуществлять контекстный поиск с помощью специального параметра `search`. Подробнее можно узнать по [ссылке](#header-контекстный-поиск).

Поиск среди объектов услуг на соответствие поисковой строке будет осуществлён по следующим полям:
+ по наименованию Услуги **name**
+ по коду Услуги **code**

## Услуги [/entity/service]
### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) объекта
+ **id** - ID Услуги в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **owner** - Ссылка на Владельца (Сотрудника) в формате [Метаданных](#header-метаданные)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника в формате [Метаданных](#header-метаданные)
+ **syncId** - ID синхронизации. После заполнения недоступен для изменения.
+ **version** - Версия сущности `Только для чтения`
+ **updated** - Момент последнего обновления сущности `Только для чтения`
+ **name** - Наименование Услуги `Необходимое`
+ **description** - Описание Услуги
+ **code** - Код Услуги
+ **externalCode** - Внешний код Услуги
+ **archived** - Отметка о том, добавлен ли Услуга в архив
+ **pathName** - Наименование группы, в которую входит Услуга `Только для чтения`
+ **vat** - НДС %
+ **effectiveVat** - Реальный НДС % `Только для чтения`
+ **productFolder** - Ссылка на группу Услуги
+ **uom** - Единицы измерения
+ **minPrice** - Минимальная цена
+ **salePrices** - Цены продажи
+ **attributes** - Дополнительные поля Услуги в формате [Метаданных](#header-метаданные)
+ **buyPrice** - Закупочная цена
+ **barcodes** - Массив штрихкодов Услуги
+ **paymentItemType** - Признак предмета расчета
  + **SERVICE** - Услуга
  + **WORK** - Работа
  + **PROVIDING_RID** - Предоставление РИД
  + **COMPOUND_PAYMENT_ITEM** - Составной предмет расчета
  + **ANOTHER_PAYMENT_ITEM** - Иной предмет расчета
+ **discountProhibited** - Признак запрета скидок.
+ **taxSystem** - Код системы налогообложения.

| Система налогообложения    | Значение поля taxSystem                |
| ---------------------------|:---------------------------------------|
| Совпадает с группой        | TAX_SYSTEM_SAME_AS_GROUP               |
| ОСН                        | GENERAL_TAX_SYSTEM                     |
| УСН. Доход                 | SIMPLIFIED_TAX_SYSTEM_INCOME           |
| УСН. Доход-Расход          | SIMPLIFIED_TAX_SYSTEM_INCOME_OUTCOME   |
| ЕСХН                       | UNIFIED_AGRICULTURAL_TAX               |
| ЕНВД                       | PRESUMPTIVE_TAX_SYSTEM                 |
| Патент                     | PATENT_BASED                           |

Атрибут **pathName** сам по себе является атрибутом только для чтения, однако его можно изменить
с помощью обновления атрибута **productFolder**.

### Атрибуты доступные для фильтрации
+ **id** - ID Услуги в формате UUID
+ **owner** - Ссылка на Владельца (Сотрудника)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника
+ **syncId** - ID синхронизации
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **updatedBy** - Автор последнего обновления сущности в формате `uid` (`admin@admin`)
+ **name** - Наименование Услуги
+ **description** - Описание Услуги
+ **code** - Код Услуги
+ **externalCode** - Внешний код Услуги
+ **archived** - Отметка о том, добавлен ли Услуга в архив
+ **pathName** - Наименование группы, в которую входит Услуга

### Атрибуты доступные для сортировки
+ **id** - ID Услуги в формате UUID
+ **syncId** - ID синхронизации
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **name** - Наименование Услуги
+ **code** - Код Услуги
+ **externalCode** - Внешний код Услуги
+ **archived** - Отметка о том, добавлен ли Услуга в архив
+ **pathName** - Наименование группы, в которую входит Услуга

### Атрибуты вложенных сущностей

### Метаданные Услуг
Метаданные Услуг содержат информацию о дополнительных полях и типах цен Услуг.

Типы цен - поле **priceType**, вложенное в объекты коллекции **salePrices**. Его значение - наименование соответствующего типа цен.

Посмотреть все созданные в основном интерфейсе доп. поля Услуг,
а также все типы цен можно с помощью запроса на получение метаданных Услуг.
Ответ - объект, со следующей структурой:
+ **meta** - Метаданные
+ **attributes** - коллекция всех существующих доп. полей Товаров в формате [Метаданных](#header-метаданные)
+ **priceTypes** - коллекция всех существующих типов цен.
+ **createShared** - создавать новые услуги с меткой "Общий"

Структуры объектов отдельных коллекций:

#### Тип цены
+ **name** - Наименование типа цен

О работе с доп. полями Услуг можно прочитать [здесь](#header-работа-с-дополнительными-полями)

#### Цены продажи
+ **value** - Значение цены
+ **currency** - Ссылка на валюту в формате [Метаданных](#header-метаданные)
+ **priceType** - Тип цены

#### Закупочная цена
+ **value** - Значение цены
+ **currency** - Ссылка на валюту в формате [Метаданных](#header-метаданные)


#### Группа Услуги
+ **meta** - Метаданные, содержащие ссылку на группу Услуги.
Описание сущности Группа вы можете посмотреть [здесь](#группа-товаров).
Обновление этого атрибута также обновит атрибут **pathName**.

#### Особенности фильтрации поля archived
Если одновременно осуществляется фильтрация по полям **id** и **archived**, то фильтрация по полю **archived** не учитывается.


### Получить список Услуг [GET]
Запрос на получение всех Услуг для данной учётной записи.
Результат: Объект JSON, включающий в себя поля:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой [Услуги](#услуга-услуги).

+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Услуг.
  + Body
      <!-- include(body/service/get_list_response.json) -->

### Создать Услугу[POST]
Создать новую Услугу.
### Описание
Услуга создаётся на основе переданного объекта JSON,
который содержит представление новой Услуги.
Результат - JSON представление созданной Услуги. Для создания новой Услуги,
необходимо и достаточно указать в переданном объекте не пустое поле `name`

При создании Услуги с указанным массивом штрихкодов, каждый штрихкод проходит проверку на то, к какому типу он относится EAN 8, EAN 13.
Если же штрихкод не относится ни к одному из этих 2 типов, он записывается как штрихкод типа Code 128.
При создании Услуги отсутствует возможность указать штрихкод в массиве штрихкодов, который будет иметь тип UPC. Данное поведение является
 ограничением JSON API 1.1

+ Request Пример 1 (application/json)
Пример наиболее полного по количеству полей запроса.
  + Body
        <!-- include(body/service/post_request_long.json) -->


+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданной Услуги.
  + Body
        <!-- include(body/service/post_long_response.json) -->


+ Request Пример 2 (application/json)
Пример запроса на создание Услуги с единственным необходимым полем.
  + Body
        <!-- include(body/service/post_request_short.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданной Услуги.
  + Body
        <!-- include(body/service/post_short_response.json) -->

+ Request Пример с доп. полями (application/json)
Пример запроса на создание Услуги с доп. полями.
  + Body
        <!-- include(body/service/post_with_attributes_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Товара.
  + Body
        <!-- include(body/service/post_with_attributes_response.json) -->

### Удалить Услугу [DELETE /entity/service/{id}]
Запрос на удаление Услуги с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Услуги

+ Response 200 (application/json)
Успешное удаление Услуги.
  + Body

## Метаданные Услуг [/entity/service/metadata]
### Метаданные Услуг [GET]
Запрос на получение метаданных Услуг. Результат - объект JSON, включающий в себя:
+ **meta** - Метаданные
+ **attributes** - коллекция всех существующих доп. полей Товаров в формате [Метаданных](#header-метаданные)
+ **priceTypes** - коллекция всех существующих типов цен.
+ **createShared** - создавать новые комплекты с меткой "Общий"

Структура отдельного объекта, представляющего доп. поле подробно описана в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями).

Структура отдельного объекта, представляющего тип цены:
+ **name** - Наименование типа цен

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление доп. полей Услуг.
  + Body
        <!-- include(body/service/get_metadata.json) -->

## Отдельное доп. поле [/entity/service/metadata/attributes/{id}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Доп. поля
### Отдельное доп. поле [GET]
Запрос на получение информации по отдельному дополнительному полю.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельного доп. поля.
  + Body
        <!-- include(body/service/metadata_by_id.json) -->

## Услуга [/entity/service/{id}]
Отдельная Услуга, обращение к которой происходит по значению его id.

+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Услуги.

### Получить Услугу[GET]
Запрос на получение Услуги с указанным id.

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Услуги.
  + Body
        <!-- include(body/service/get_by_id_response.json) -->

### Изменить Услугу[PUT]
Обновить существующую Услугу.
Типы цен в ценах продаж и дополнительные поля обновляются как элементы вложенных коллекций:
+ Если в текущем объекте у какого-то из доп. полей / типов цен нет значения,
а в переданной коллекции оно есть - значение записывается в доп. поле / тип цены.
+ Если же у данного атрибута значение уже присутствует - оно перезаписывается на переданное.
+ Если у данного атрибута в составе объекта значение присутствует, однако оно отсутствует
в передаваемой в теле запроса коллекции (не передаётся совсем), то значение атрибута объекта не изменяется.

При обновлении Услуги с указанным в теле запроса массивом штрихкодов, каждый штрихкод проходит проверку на то, к какому типу он относится EAN 8, EAN 13. Если же штрихкод не относится ни к одному из этих 2 типов, он записывается как штрихкод типа Code 128.
Переданный массив штрихкодов полностью заменяет предыдущий массив штрихкодов. При обновлении Услуги отсутствует возможность указать штрихкод в массиве штрихкодов, который будет иметь тип UPC. Данное поведением является ограничение JSON API 1.1

+ Request Пример (application/json)
Пример запроса на обновление Услуги
  + Body
        <!-- include(body/service/put_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление обновлённой Услуги.
  + Body
        <!-- include(body/service/put_response.json) -->
+ Request Пример с доп. полями (application/json)
Пример запроса на изменение Услуги с дополнительными полями.
  + Body
        <!-- include(body/service/put_with_attributes_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление обновлённой Услуги.
  + Body
        <!-- include(body/service/put_with_attributes_response.json) -->

# Data Structures
## Service (object)
###Properties
+ meta:(MetaRef, optional) - Метаданные
+ id: `24124124-4124-4124124` (string, optional) - ID в формате UUID
+ accountId: `121252-12412-4124141-24124`(string, optional) - ID учетной записи
+ version: 1(string, optional) - Версия сущности
+ updated: `2016-04-04 12:20:10`(string, optional) - Момент последнего обновления сущности
+ deleted: `2016-04-04 12:20:10`(string, optional) - Момент последнего удаления сущности
+ name: Товар1 (string, optional) - Наименование Услуги
+ description: Это Услуга1(string, optional) - Описание Услуги
+ code: 124(string, optional) - Код
+ externalCode: 456(string, optional) - Внешний код
+ archived: true (boolean, optional) - Добавлена ли Услуга в архив
+ pathName: Группа1 (string, optional) - Наименование группы, в которую входит Услуга
+ vat: 10 (string, optional) - НДС %
+ effectiveVat: 10 (string, optional)- Реальный НДС %
+ productFolder(MetaRef, optional) - Ссылка на сущность группы Услуги
+ uom: шт (string, optional) - Единицы измерения
+ minPrice: (object, optional) - Минимальная цена
+ salePrices: (array[Sale Price], optional) - Цена продажи
+ attributes: (Meta, optional) - Ссылка на атрибуты Услуги

## Service List
###Properties
+ context: (Context, required)
+ meta: (Meta, required)
+ rows: (array[Service], required, fixed) - Массив Услуг

## Service request long (object)
+ name: myName (string, required) - Наименование Услуги
+ code: one1 (string, optional) - Код
+ externalCode: 456 (string, optional) - Внешний код
+ description: best CP ever(string, optional) - Описание Услуги
+ vat: (string, optional) - НДС %
+ uom: см (string, optional) - Единицы измерения

## Service request short (object)
+ name:   myName (string, required) - Наименование Услуги

## Sale Price (object)
