# Group Склад

## Склады [/entity/store]
По данной сущности можно осуществлять контекстный поиск с помощью специального параметра `search`. Подробнее можно узнать по [ссылке](#header-контекстный-поиск).

Поиск среди объектов складов на соответствие поисковой строке будет осуществлён по следующим полям:
+ По наименованию Склада **name**
+ По коду Склада **code**

### Атрибуты сущности
+ **meta** - [Метаданные](#header-метаданные) о Складе
+ **id** - ID в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **owner** - Ссылка на Владельца (Сотрудника) в формате [Метаданных](#header-метаданные)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника в формате [Метаданных](#header-метаданные)
+ **version** - Версия сущности `Только для чтения`
+ **updated** - Момент последнего обновления сущности `Только для чтения`
+ **name** - Наименование Склада `Необходимое`
+ **description** - комментарий к Складу
+ **code** - Код Склада
+ **externalCode** - Внешний код Склада
+ **archived** - Добавлен ли Склад в архив
+ **address** - Адрес
+ **addressFull** - Адрес с детализацией по отдельным полям.
+ **parent** - Родительский склад (Группа)
+ **pathName** - Группа Склада
+ **attributes** - Дополнительные поля Склада в формате [Метаданных](#header-метаданные)

#### Аттрибуты сущности Адрес
+ **postalCode** - Почтовый индекс
+ **country** - Ссылка на страну в формате [Метаданных](#header-метаданные)
+ **region** - Ссылка на регион в формате [Метаданных](#header-метаданные)
+ **city** - Город
+ **street** - Улица
+ **house** - Дом (Максимальная длина - 30 символов)
+ **apartment** - Квартира (Максимальная длина - 30 символов)
+ **addInfo** - Другое
+ **comment** - Комментарий

Строка адреса является конкатенацией полей структурированного адреса в следующем порядке: postalCode -> country -> region -> city -> street -> house -> apartment -> addInfo, используя запятую в качестве разделителя.
При передаче в МойСклад сущностей с адресом используйте либо строковый адрес, либо структурированнй.
При передаче обоих адресов строковый будет игнорирован.
При передаче только строкового он будет отражаться как в строковом поле, так и в addInfo структурированного адреса.

О работе с доп. полями Складов можно прочитать [здесь](#header-работа-с-дополнительными-полями)

### Атрибуты доступные для фильтрации
+ **id** - ID в формате UUID
+ **owner** - Ссылка на Владельца (Сотрудника)
+ **shared** - Общий доступ
+ **group** - Отдел сотрудника
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **updatedBy** - Автор последнего обновления сущности в формате `uid` (`admin@admin`)
+ **name** - Наименование Склада
+ **description** - комментарий к Складу
+ **code** - Код Склада
+ **externalCode** - Внешний код Склада
+ **archived** - Добавлен ли Склад в архив
+ **address** - Адрес Склада
+ **parent** - Родительский склад (Группа)
+ **pathName** - Группа Склада

### Атрибуты доступные для сортировки
+ **id** - ID в формате UUID
+ **version** - Версия сущности
+ **updated** - Момент последнего обновления сущности
+ **name** - Наименование Склада
+ **description** - комментарий к Складу
+ **code** - Код Склада
+ **externalCode** - Внешний код Склада
+ **archived** - Добавлен ли Склад в архив
+ **pathName** - Группа Склада

### Получить Склады [GET]
Получить список всех Складов.
Результат: Объект JSON, включающий в себя поля:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой [Склады](#склад-склады).
+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Складов.
  + Body
        <!-- include(body/store/get_list.json) -->

### Создать Склад [POST]
Создать новый Склад.
### Описание
Склад создаётся на основе переданного объекта JSON,
который содержит представление нового Склада.
Необходимое для создания поле - `name` не должно быть пустым.

+ Request Пример (application/json)
Пример запроса на создание нового Склада.
  + Body
        <!-- include(body/store/post_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Склада.
  + Body
        <!-- include(body/store/post_response.json) -->

+ Request Пример с доп полями (application/json)
Пример запроса на создание нового Склада с доп. полями в теле запроса.
  + Body
        <!-- include(body/store/post_with_attributes_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданного Склада.
  + Body
        <!-- include(body/store/post_with_attributes_response.json) -->

### Удалить Склад [DELETE /entity/store/{id}]
Запрос на удаление Склада с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Склада

+ Response 200 (application/json)
Успешное удаление Склада.
  + Body

## Метаданные Складов [/entity/store/metadata]
### Метаданные Складов [GET]
Запрос на получение метаданных Складов. Результат - объект JSON, включающий в себя:
+ **meta** - Ссылка на метаданные Складов
+ **attributes** - Массив объектов доп. полей Складов в формате [Метаданных](#header-метаданные)
+ **createShared** - создавать новые Склады с меткой "Общий"

Структура отдельного объекта, представляющего доп. поле подробно описана в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями).

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление доп. полей Складов.
  + Body
        <!-- include(body/store/get_metadata.json) -->

## Отдельное доп. поле [/entity/store/metadata/attributes/{id}]
+ Parameters
  + id: `5290a290-0313-11e6-9464-e4de00000020` (required, string) - id Доп. поля
### Отдельное доп. поле [GET]
Запрос на получение информации по отдельному дополнительному полю.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельного доп. поля.
  + Body
        <!-- include(body/store/metadata_by_id.json) -->

## Склад [/entity/store/{id}]

+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Склада.
### Получить Склад [GET]
Запрос на получение отдельного Склада с указанным id.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Склада с указанным id.
  + Body
        <!-- include(body/store/get_by_id.json) -->

### Изменить Склад [PUT]
### Описание
Обновляется представление Склада с указанным id.
В теле запроса можно указать только те поля, которые необходимо изменить у Склада,
кроме полей, помеченных `Только для чтения` в описании [атрибутов Склада](#склад-склады).

+ Request Пример (application/json)
Пример запроса на обновление существующего Склада.
  + Body
        <!-- include(body/store/put_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление обновлённого Склада.
  + Body
        <!-- include(body/store/put_response.json) -->

+ Request Пример с доп полями (application/json)
Пример запроса на обновление существующего Склада с доп полями в теле запроса.
  + Body
        <!-- include(body/store/put_with_attributes_request.json) -->
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление обновлённого Склада.
  + Body
        <!-- include(body/store/put_with_attributes_response.json) -->


# Data Structures

## Store (Legendable Entity)
###Properties
+ address: (string, required) - Адрес Склада
+ pathName: (string, required) - Группа Склада

## Store List (object)
+ context: (Context, required)
+ meta: (Meta, required)
+ rows: (array[Store], required, fixed) - Массив Складов
