# Group Модификация

## Модификации [/entity/variant]
Средствами JSON API можно создавать и обновлять сведения о Модификациях товаров, запрашивать списки Модификаций товаров и сведения по отдельным Модификациям. Кодом сущности для Модификации в составе JSON API является ключевое слово **variant**. Больше о Модификациях товаров и работе с ними в основном интерфейсе вы можете прочитать в нашей службе поддержки по
 [этой ссылке](https://support.moysklad.ru/hc/ru/articles/203325413-%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%B8-%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2),
 а также больше о работе с товарами [здесь](https://support.moysklad.ru/hc/ru/sections/200564973-%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D1%8B-%D0%B8-%D1%81%D0%BA%D0%BB%D0%B0%D0%B4).
По данной сущности можно осуществлять контекстный поиск с помощью специального параметра `search`. Подробнее можно узнать по [ссылке](#header-контекстный-поиск). Поиск с параметром search отличается от других тем, что поиск не префиксный, без токенизации и идет только по одному полю одновременно. Ищет такие строки, в которые входит значение строки поиска.

Поиск среди объектов модификаций на соответствие поисковой строке будет осуществлён по следующим полям:
+ по наименованию товара с Модификацией **name**

### Атрибуты Сущности
+ **meta** - [Метаданные](#header-метаданные) объекта
+ **id** - ID услуги в формате UUID `Только для чтения`
+ **accountId** - ID учетной записи `Только для чтения`
+ **version** - Версия сущности `Только для чтения`
+ **updated** - Момент последнего обновления сущности `Только для чтения`
+ **name** - Наименование товара с Модификацией
+ **code** - Код Модификации
+ **externalCode** - Внешний код Модификации
+ **archived** - Добавлен ли товар в архив
+ **characteristics** - Характеристики Модификации `Необходимое`
+ **minPrice** - Минимальная цена
+ **buyPrice** - Закупочная цена
+ **salePrices** - Цены продажи
+ **barcodes** - Массив штрихкодов модификации
+ **product** - [Метаданные](#header-метаданные), представляющие с собой ссылку на [товар](#товар-товары), к которому привязана Модификация. `Необходимое`
+ **things** - Серийные номера `Только для чтения`
+ **discountProhibited** - Признак запрета скидок.

### Атрибуты доступные для фильтрации
+ **name** - Наименование товара с Модификацией
+ **code** - Код Модификации
+ **externalCode** - Внешний код Модификации
+ **archived** - Добавлен ли товар в архив

### Атрибуты доступные для сортировки
+ **code** - Код Модификации
+ **externalCode** - Внешний код Модификации
+ **archived** - Добавлен ли товар в архив

### Атрибуты вложенных сущностей
#### Метаданные Модификаций
Метаданные Модификаций содержат информацию о дополнительных полях Товаров, к которым привязаны Модификации,
характеристиках Модификаций, а также о типах цен.
Характеристики Модификации - внутренняя коллекция **characteristics**. Представлена в виде массива объектов с полями:
+ **meta** - метаданные характеристики
+ **id** - id соответствующей характеристики.
+ **name** - наименование характеристики.
+ **value** - значение характеристики.
Типы цен - поле **priceType**, вложенное в объекты коллекции **salePrices**. Его значение - наименование соответствующего типа цен.

Посмотреть все созданные в основном интерфейсе характеристики Модификаций, доп. поля Товаров, к которым они привязаны,
а также все типы цен можно с помощью запроса на получение метаданных Модификаций.
Ответ - объект, со следующей структурой:
+ **meta** - Метаданные
+ **attributes** - коллекция всех существующих доп. полей Товаров в формате [Метаданных](#header-метаданные)
+ **characteristics** - коллекция всех созданных характеристик Модификаций.
+ **priceTypes** - коллекция всех существующих типов цен.
+ **createShared** - создавать новые модификации с меткой "Общий"

Структуры отдельных объектов коллекций:

##### *characteristics*
+ **meta** - Метаданные характеристики
+ **id** - ID характеристики
+ **name** - Наименование характеристики
+ **type** - Тип значения характеристики
+ **required** - Флажок о том, является ли характеристика обязательной

##### *priceTypes*
+ **name** - Наименование типа цен

Подробную информацию о работе с доп. полями Товаров и Услуг можно прочитать в разделах
[Метаданные Товаров](#header-метаданные-товаров) и [Метаданные Услуг](#header-метаданные-услуг).

#### Цены продажи
Если у модификации не заданы отдельные цены продажи, в ответе будут выведены соответствующие цены продажи товара.
+ **value** - Значение цены
+ **currency** - Ссылка на валюту в формате [Метаданных](#header-метаданные)
+ **priceType** - Тип цены

### Получить список Модификаций [GET]
Запрос на получение списка всех Модификаций на данной учётной записи.
Результат успешного запроса - JSON представление списка Модификаций с перечисленными полями:
- **meta** [Метаданные](#header-метаданные) о выдаче,
- **context** - [Метаданные](#header-метаданные) о сотруднике, выполнившем запрос.
- **rows** - Массив JSON объектов, представляющих собой [Модификации](#модификация-модификации).

Возможна фильтрация списка Модификаций по **id** товара - параметр **productid**.
Подробнее про данный параметр можно посмотреть в разделе [Фильтрация выборки с помощью параметра filter](#header-фильтрация-выборки-с-помощью-параметра-filter)

+ Parameters
  + limit: 100 (optional, enum[number])
  Максимальное количество сущностей для извлечения.
  <p>
    <code>Допустимые значения 1 - 100</code>
  </p>
      + Default: `25`
  + offset: 40 (optional, number)
    Отступ в выдаваемом списке сущностей
      + Default: `0`

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление списка Модификаций.
  + Body
        <!-- include(body/variant/get_list.json) -->

### Создать Модификацию [POST]
Создать новую Модификацию. Для создания новой Модификации необходимы поля **product**, **characteristics**.
Поле **characteristics** указывается как массив объектов со следующей структурой:
+ **id** - uuid характеристики
+ **value** - значение характеристики
Если поле **id** не указано у какого-либо объекта характеристики, производится поиск соответствующей этому объекту
характеристики по полю **name**. Если же не указаны ни **id** ни **name** произойдёт ошибка.
+ Request Пример (application/json)
Пример запроса на создание новой Модификации, привязанной к существующему товару.
  + Body
        <!-- include(body/variant/post_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление созданной Модификации.
  + Body
        <!-- include(body/variant/post_response.json) -->

### Удалить Модификацию [DELETE /entity/variant/{id}]
Запрос на удаление Модификации с указанным id.
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Модификации

+ Response 200 (application/json)
Успешное удаление Модификации.
  + Body

## Метаданные Модификаций [/entity/variant/metadata]
### Метаданные Модификаций [GET]
Запрос на получение метаданных Модификаций. Результат - объект JSON, включающий в себя:
+ **meta** - Метаданные
+ **attributes** - коллекция всех существующих доп. полей Товаров в формате [Метаданных](#header-метаданные)
+ **characteristics** - коллекция всех созданных характеристик Модификаций.
+ **priceTypes** - коллекция всех существующих типов цен.
+ **createShared** - создавать новые комплекты с меткой "Общий"

Структура отдельного объекта, представляющего доп. поле подробно описана в разделе [Работа с дополнительными полями](#header-работа-с-дополнительными-полями).

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление метаданных модификации.
  + Body
        <!-- include(body/variant/get_metadata.json) -->

## Отдельное доп. поле [/entity/variant/metadata/attributes/{id}]
+ Parameters
  + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id Доп. поля
### Отдельное доп. поле [GET]
Запрос на получение информации по отдельному дополнительному полю.
+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление отдельного доп. поля.
  + Body
        <!-- include(body/variant/metadata_by_id.json) -->

## Модификация [/entity/variant/{id}]
Работа с Модификацией с указанным id.
  + Parameters
    + id: `7944ef04-f831-11e5-7a69-971500188b19` (required, string) - id серии
### Получить Модификацию [GET]
Запрос на получение представления Модификации с указанным id.
  + Response 200 (application/json)
  Успешный запрос. Результат - JSON представление Модификации.
    + Body
          <!-- include(body/variant/get_by_id.json) -->

### Изменить Модификацию [PUT]
Запрос на обновление Модификации с указанным id.
Типы цен в ценах продаж обновляются как элементы вложенных коллекций:
+ Если в текущем объекте у какого-то из доп. полей / типов цен нет значения,
а в переданной коллекции оно есть - значение записывается в доп. поле / тип цены.
+ Если же у данного атрибута значение уже присутствует - оно перезаписывается на переданное.
+ Если у данного атрибута в составе объекта значение присутствует, однако оно отсутствует
в передаваемой в теле запроса коллекции (не передаётся совсем), то значение атрибута объекта не изменяется.

При обновлении характеристик Модификации поле **characteristics** указывается как
массив объектов со следующей структурой:
+ **id** - uuid характеристики
+ **name** - наименование характеристики
+ **value** - значение характеристики
Если поле **id** не указано у какого-либо объекта характеристики, производится поиск соответствующей этому объекту
характеристики по полю **name**. Если же не указаны ни **id** ни **name** произойдёт ошибка.
При обновлении, поле **characteristics** в теле запроса обрабатывается как "все характеристики модификации",
т.е. полностью заменяет предыдущий массив характеристик. Если какая то из характеристик, имевшая значение в обновляемом
объекте не указана в запросе на обновление, после запроса её значение будет аннулированно.

+ Request Пример (application/json)
Пример запроса на обновление Модификации.
  + Body
        <!-- include(body/variant/put_request.json) -->

+ Response 200 (application/json)
Успешный запрос. Результат - JSON представление Модификации.
  + Body
        <!-- include(body/variant/put_response.json) -->


# Data Structures

## Variant (object)
###Properties
+ meta:(MetaRef, optional) - Метаданные
+ id: `24124124-4124-4124124` (string, optional) - ID в формате UUID
+ accountId: `121252-12412-4124141-24124`(string, optional) - ID учетной записи
+ version: 1(string, optional) - Версия сущности
+ updated: `2016-04-04 12:20:10`(string, optional) - Момент последнего обновления сущности
+ deleted: `2016-04-04 12:20:10`(string, optional) - Момент последнего удаления сущности
+ name: Товар1 (string, optional) - Наименование товара с Модификацией
+ code: 124(string, optional) - Код
+ externalCode: 456(string, optional) - Внешний код
+ archived: true (boolean, optional) - Добавлен ли товар в архив
+ characteristics: (object, required) - Характеристики Модификации
+ buyPrice: (object, optional) - Цена закупки
+ salePrices: (array[], optional) - Цена продажи
+ product: (MetaRef, required) - Ссылка на продукт, к которому относится Модификация

## Variant List
###Properties
+ context: (Context, required)
+ meta: (Meta, required)
+ rows: (array[Variant], required, fixed) - Массив Модификаций
